;;; Copyright (c) 2004-2026 Yoshikatsu Fujita / LittleWing Company Limited.
;;; See LICENSE file for terms and conditions of use.

(define-module (core json)
  (export generate-json-string parse-json-string)
  (import (core base)
          (core let-values))

  (define (alist? obj)
    (and (list? obj)
         (not (null? obj))
         (every (lambda (x)
                  (and (pair? x)
                       (string? (car x))))
                obj)))

  (define (hex-digit n)
    (string-ref "0123456789abcdef" n))

  (define (write-json-string str port)
    (put-char port #\")
    (let ((len (string-length str)))
      (let loop ((i 0))
        (if (< i len)
            (let* ((c (string-ref str i))
                   (code (char->integer c)))
              (cond
                ((= code 34) (put-string port "\\\""))
                ((= code 92) (put-string port "\\\\"))
                ((= code 10) (put-string port "\\n"))
                ((= code 13) (put-string port "\\r"))
                ((= code 9)  (put-string port "\\t"))
                ((= code 8)  (put-string port "\\b"))
                ((= code 12) (put-string port "\\f"))
                ((< code 32)
                 (put-string port "\\u00")
                 (put-char port (hex-digit (quotient code 16)))
                 (put-char port (hex-digit (remainder code 16))))
                (else (put-char port c)))
              (loop (+ i 1))))))
    (put-char port #\"))

  (define (serialize-to-port obj port)
    (cond
      ((null? obj)
       (put-string port "null"))
      ((boolean? obj)
       (put-string port (if obj "true" "false")))
      ((number? obj)
       (put-string port (number->string obj)))
      ((string? obj)
       (write-json-string obj port))
      ((symbol? obj)
       (write-json-string (symbol->string obj) port))
      ((alist? obj)
       (write-json-object obj port))
      ((vector? obj)
       (write-json-array (vector->list obj) port))
      (else
       (error "generate-json-string" "unsupported type for JSON serialization" obj))))

  (define (write-json-array lst port)
    (put-char port #\[)
    (if (not (null? lst))
        (begin
          (serialize-to-port (car lst) port)
          (let loop ((rest (cdr lst)))
            (if (not (null? rest))
                (begin
                  (put-string port ", ")
                  (serialize-to-port (car rest) port)
                  (loop (cdr rest)))))))
    (put-char port #\]))

  (define (write-json-object alist port)
    (put-string port "{ ")
    (serialize-pair (car alist) port)
    (let loop ((rest (cdr alist)))
      (if (not (null? rest))
          (begin
            (put-string port ", ")
            (serialize-pair (car rest) port)
            (loop (cdr rest)))))
    (put-string port " }"))

  (define (serialize-pair pair port)
    (let ((key (car pair))
          (val (cdr pair)))
      (cond
        ((string? key)
         (write-json-string key port))
        (else
         (error "generate-json-string" "JSON object key must be a string" key)))
      (put-string port ": ")
      (serialize-to-port val port)))

  (define (generate-json-string obj)
    (let-values (((port extract) (open-string-output-port)))
      (serialize-to-port obj port)
      (extract)))

  ;; Parsing JSON

  (define (skip-whitespace str i len)
    (if (< i len)
        (let ((c (string-ref str i)))
          (if (or (char=? c #\space)
                  (char=? c #\newline)
                  (char=? c #\return)
                  (char=? c #\tab))
              (skip-whitespace str (+ i 1) len)
              i))
        i))

  (define (hex-value c)
    (let ((code (char->integer c)))
      (cond
        ((and (>= code 48) (<= code 57)) (- code 48))       ; '0'-'9'
        ((and (>= code 97) (<= code 102)) (- code 87))      ; 'a'-'f'
        ((and (>= code 65) (<= code 70)) (- code 55))       ; 'A'-'Z'
        (else #f))))

  (define (parse-string str i len)
    (if (>= i len)
        (error "parse-json-string" "unexpected EOF inside string")
        (let ((c (string-ref str i)))
          (if (char=? c #\")
              (let loop ((idx (+ i 1)) (acc '()))
                (if (>= idx len)
                    (error "parse-json-string" "unexpected EOF inside string")
                    (let ((ch (string-ref str idx)))
                      (cond
                        ((char=? ch #\")
                         (values (list->string (reverse acc)) (+ idx 1)))
                        ((char=? ch #\\)
                         (if (>= (+ idx 1) len)
                             (error "parse-json-string" "unexpected EOF in escape sequence")
                             (let ((esc (string-ref str (+ idx 1))))
                               (cond
                                 ((char=? esc #\") (loop (+ idx 2) (cons #\" acc)))
                                 ((char=? esc #\\) (loop (+ idx 2) (cons #\\ acc)))
                                 ((char=? esc #\/) (loop (+ idx 2) (cons #\/ acc)))
                                 ((char=? esc #\b) (loop (+ idx 2) (cons (integer->char 8) acc)))
                                 ((char=? esc #\f) (loop (+ idx 2) (cons (integer->char 12) acc)))
                                 ((char=? esc #\n) (loop (+ idx 2) (cons #\newline acc)))
                                 ((char=? esc #\r) (loop (+ idx 2) (cons (integer->char 13) acc)))
                                 ((char=? esc #\t) (loop (+ idx 2) (cons #\tab acc)))
                                 ((char=? esc #\u)
                                  (if (>= (+ idx 5) len)
                                      (error "parse-json-string" "incomplete hex escape sequence")
                                      (let ((h1 (hex-value (string-ref str (+ idx 2))))
                                            (h2 (hex-value (string-ref str (+ idx 3))))
                                            (h3 (hex-value (string-ref str (+ idx 4))))
                                            (h4 (hex-value (string-ref str (+ idx 5)))))
                                        (if (and h1 h2 h3 h4)
                                            (let ((val (+ (* h1 4096) (* h2 256) (* h3 16) h4)))
                                              (loop (+ idx 6) (cons (integer->char val) acc)))
                                            (error "parse-json-string" "invalid hex escape sequence")))))
                                 (else (error "parse-json-string" "invalid escape char" esc))))))
                        (else
                         (loop (+ idx 1) (cons ch acc)))))))
              (error "parse-json-string" "string must begin with double quote" c)))))

  (define (parse-number str i len)
    (let loop ((idx i))
      (if (< idx len)
          (let ((c (string-ref str idx)))
            (if (or (char=? c #\-)
                    (char=? c #\+)
                    (char=? c #\.)
                    (char=? c #\e)
                    (char=? c #\E)
                    (and (char>=? c #\0) (char<=? c #\9)))
                (loop (+ idx 1))
                (let ((num-str (substring str i idx)))
                  (let ((num (string->number num-str)))
                    (if num
                        (values num idx)
                        (error "parse-json-string" "invalid number format" num-str))))))
          (let ((num-str (substring str i len)))
            (let ((num (string->number num-str)))
              (if num
                  (values num len)
                  (error "parse-json-string" "invalid number format" num-str)))))))

  (define (parse-array str i len)
    (let ((idx (skip-whitespace str (+ i 1) len)))
      (if (>= idx len)
          (error "parse-json-string" "unexpected EOF in array")
          (let ((c (string-ref str idx)))
            (if (char=? c #\])
                (values '#() (+ idx 1))
                (let loop ((curr-idx idx) (acc '()))
                  (let-values (((val next-idx) (parse-val str curr-idx len)))
                    (let ((post-idx (skip-whitespace str next-idx len)))
                      (if (>= post-idx len)
                          (error "parse-json-string" "unexpected EOF in array")
                          (let ((next-c (string-ref str post-idx)))
                            (cond
                              ((char=? next-c #\])
                               (values (list->vector (reverse (cons val acc))) (+ post-idx 1)))
                              ((char=? next-c #\,)
                               (loop (skip-whitespace str (+ post-idx 1) len) (cons val acc)))
                              (else
                               (error "parse-json-string" "expected ',' or ']'" next-c)))))))))))))

  (define (parse-object str i len)
    (let ((idx (skip-whitespace str (+ i 1) len)))
      (if (>= idx len)
          (error "parse-json-string" "unexpected EOF in object")
          (let ((c (string-ref str idx)))
            (if (char=? c #\})
                (values '() (+ idx 1))
                (let loop ((curr-idx idx) (acc '()))
                  (if (>= curr-idx len)
                      (error "parse-json-string" "unexpected EOF in object")
                      (let ((ch (string-ref str curr-idx)))
                        (if (char=? ch #\")
                            (let-values (((key next-idx) (parse-string str curr-idx len)))
                              (let ((colon-idx (skip-whitespace str next-idx len)))
                                (if (>= colon-idx len)
                                    (error "parse-json-string" "unexpected EOF in object")
                                    (let ((colon-c (string-ref str colon-idx)))
                                      (if (char=? colon-c #\:)
                                          (let-values (((val value-idx) (parse-val str (+ colon-idx 1) len)))
                                            (let ((post-idx (skip-whitespace str value-idx len)))
                                              (if (>= post-idx len)
                                                  (error "parse-json-string" "unexpected EOF in object")
                                                  (let ((next-c (string-ref str post-idx)))
                                                    (cond
                                                      ((char=? next-c #\})
                                                       (values (reverse (cons (cons key val) acc)) (+ post-idx 1)))
                                                      ((char=? next-c #\,)
                                                       (loop (skip-whitespace str (+ post-idx 1) len) (cons (cons key val) acc)))
                                                      (else
                                                       (error "parse-json-string" "expected ',' or '}'" next-c)))))))
                                          (error "parse-json-string" "expected ':' after key" colon-c))))))
                            (error "parse-json-string" "expected double quoted key" ch))))))))))

  (define (parse-val str i len)
    (let ((idx (skip-whitespace str i len)))
      (if (>= idx len)
          (error "parse-json-string" "unexpected EOF")
          (let ((c (string-ref str idx)))
            (cond
              ((char=? c #\{)
               (parse-object str idx len))
              ((char=? c #\[)
               (parse-array str idx len))
              ((char=? c #\")
               (parse-string str idx len))
              ((char=? c #\t)
               (if (and (< (+ idx 3) len)
                        (char=? (string-ref str (+ idx 1)) #\r)
                        (char=? (string-ref str (+ idx 2)) #\u)
                        (char=? (string-ref str (+ idx 3)) #\e))
                   (values #t (+ idx 4))
                   (error "parse-json-string" "invalid literal, expected 'true'")))
              ((char=? c #\f)
               (if (and (< (+ idx 4) len)
                        (char=? (string-ref str (+ idx 1)) #\a)
                        (char=? (string-ref str (+ idx 2)) #\l)
                        (char=? (string-ref str (+ idx 3)) #\s)
                        (char=? (string-ref str (+ idx 4)) #\e))
                   (values #f (+ idx 5))
                   (error "parse-json-string" "invalid literal, expected 'false'")))
              ((char=? c #\n)
               (if (and (< (+ idx 3) len)
                        (char=? (string-ref str (+ idx 1)) #\u)
                        (char=? (string-ref str (+ idx 2)) #\l)
                        (char=? (string-ref str (+ idx 3)) #\l))
                   (values '() (+ idx 4))
                   (error "parse-json-string" "invalid literal, expected 'null'")))
              ((or (char=? c #\-)
                   (and (char>=? c #\0) (char<=? c #\9)))
               (parse-number str idx len))
              (else
               (error "parse-json-string" "unexpected character" c)))))))

  (define (parse-json-string str)
    (let ((len (string-length str)))
      (let-values (((val next-idx) (parse-val str 0 len)))
        (let ((final-idx (skip-whitespace str next-idx len)))
          (if (= final-idx len)
              val
              (error "parse-json-string" "unexpected characters at end of string" (substring str final-idx len)))))))

) ;[end]
