;;; Copyright (c) 2004-2026 Yoshikatsu Fujita / LittleWing Company Limited.
;;; See LICENSE file for terms and conditions of use.

(define-module (core json)
  (export generate-json-string parse-json-string)
  (import (core base)
          (core let-values))

  (define (alist? obj)
    (and (list? obj)
         (not (null? obj))
         (every (lambda (x)
                  (and (pair? x)
                       (string? (car x))))
                obj)))

  (define *hex-digits* (string->vector "0123456789abcdef"))
  (define *true-vec* (string->vector "true"))
  (define *false-vec* (string->vector "false"))
  (define *null-vec* (string->vector "null"))

  (define (hex-digit n)
    (vector-ref *hex-digits* n))

  (define (write-json-string str port)
    (put-char port #\")
    (let ((in-port (open-string-input-port str)))
      (let loop ()
        (let ((c (get-char in-port)))
          (if (not (eof-object? c))
              (let ((code (char->integer c)))
                (cond
                  ((= code 34) (put-string port "\\\""))
                  ((= code 92) (put-string port "\\\\"))
                  ((= code 10) (put-string port "\\n"))
                  ((= code 13) (put-string port "\\r"))
                  ((= code 9)  (put-string port "\\t"))
                  ((= code 8)  (put-string port "\\b"))
                  ((= code 12) (put-string port "\\f"))
                  ((< code 32)
                   (put-string port "\\u00")
                   (put-char port (hex-digit (quotient code 16)))
                   (put-char port (hex-digit (remainder code 16))))
                  (else (put-char port c)))
                (loop))))))
    (put-char port #\"))

  (define (serialize-to-port obj port)
    (cond
      ((null? obj)
       (put-string port "null"))
      ((boolean? obj)
       (put-string port (if obj "true" "false")))
      ((number? obj)
       (put-string port (number->string obj)))
      ((string? obj)
       (write-json-string obj port))
      ((symbol? obj)
       (write-json-string (symbol->string obj) port))
      ((alist? obj)
       (write-json-object obj port))
      ((vector? obj)
       (write-json-array obj port))
      (else
       (error "generate-json-string" "unsupported type for JSON serialization" obj))))

  (define (write-json-array vec port)
    (put-char port #\[)
    (let ((len (vector-length vec)))
      (if (> len 0)
          (begin
            (serialize-to-port (vector-ref vec 0) port)
            (let loop ((i 1))
              (if (< i len)
                  (begin
                    (put-string port ", ")
                    (serialize-to-port (vector-ref vec i) port)
                    (loop (+ i 1))))))))
    (put-char port #\]))

  (define (write-json-object alist port)
    (put-string port "{ ")
    (serialize-pair (car alist) port)
    (let loop ((rest (cdr alist)))
      (if (not (null? rest))
          (begin
            (put-string port ", ")
            (serialize-pair (car rest) port)
            (loop (cdr rest)))))
    (put-string port " }"))

  (define (serialize-pair pair port)
    (let ((key (car pair))
          (val (cdr pair)))
      (cond
        ((string? key)
         (write-json-string key port))
        (else
         (error "generate-json-string" "JSON object key must be a string" key)))
      (put-string port ": ")
      (serialize-to-port val port)))

  (define (generate-json-string obj)
    (let-values (((port extract) (open-string-output-port)))
      (serialize-to-port obj port)
      (extract)))

  ;; Parsing JSON

  (define (hex-value c)
    (let ((code (char->integer c)))
      (cond
        ((and (>= code 48) (<= code 57)) (- code 48))       ; '0'-'9'
        ((and (>= code 97) (<= code 102)) (- code 87))      ; 'a'-'f'
        ((and (>= code 65) (<= code 70)) (- code 55))       ; 'A'-'Z'
        (else #f))))

  (define (parse-json-string input)
    (let* ((port (if (string? input)
                     (open-string-input-port input)
                     input))
           (lookahead (get-char port)))
      (define (peek) lookahead)
      (define (next)
        (let ((c lookahead))
          (set! lookahead (get-char port))
          c))

      (define (skip-whitespace)
        (let ((c (peek)))
          (cond
            ((eof-object? c) #f)
            ((or (char=? c #\space)
                 (char=? c #\newline)
                 (char=? c #\return)
                 (char=? c #\tab))
             (next)
             (skip-whitespace)))))

      (define (parse-string)
        (let ((quote-c (next)))
          (if (not (char=? quote-c #\"))
              (error "parse-json-string" "string must begin with double quote" quote-c)))
        (let loop ((acc '()))
          (let ((c (next)))
            (cond
              ((eof-object? c)
               (error "parse-json-string" "unexpected EOF inside string"))
              ((char=? c #\")
               (list->string (reverse acc)))
              ((char=? c #\\)
               (let ((esc (next)))
                 (cond
                   ((eof-object? esc)
                    (error "parse-json-string" "unexpected EOF in escape sequence"))
                   ((char=? esc #\") (loop (cons #\" acc)))
                   ((char=? esc #\\) (loop (cons #\\ acc)))
                   ((char=? esc #\/) (loop (cons #\/ acc)))
                   ((char=? esc #\b) (loop (cons (integer->char 8) acc)))
                   ((char=? esc #\f) (loop (cons (integer->char 12) acc)))
                   ((char=? esc #\n) (loop (cons #\newline acc)))
                   ((char=? esc #\r) (loop (cons (integer->char 13) acc)))
                   ((char=? esc #\t) (loop (cons #\tab acc)))
                   ((char=? esc #\u)
                    (let* ((h1 (next))
                           (h2 (next))
                           (h3 (next))
                           (h4 (next)))
                      (if (or (eof-object? h1) (eof-object? h2) (eof-object? h3) (eof-object? h4))
                          (error "parse-json-string" "incomplete hex escape sequence")
                          (let ((v1 (hex-value h1))
                                (v2 (hex-value h2))
                                (v3 (hex-value h3))
                                (v4 (hex-value h4)))
                            (if (and v1 v2 v3 v4)
                                (let ((val (+ (* v1 4096) (* v2 256) (* v3 16) v4)))
                                  (loop (cons (integer->char val) acc)))
                                (error "parse-json-string" "invalid hex escape sequence"))))))
                   (else (error "parse-json-string" "invalid escape char" esc)))))
              (else
               (loop (cons c acc)))))))

      (define (parse-number)
        (let loop ((acc '()))
          (let ((c (peek)))
            (if (and (not (eof-object? c))
                     (or (char=? c #\-)
                         (char=? c #\+)
                         (char=? c #\.)
                         (char=? c #\e)
                         (char=? c #\E)
                         (and (char>=? c #\0) (char<=? c #\9))))
                (begin
                  (next)
                  (loop (cons c acc)))
                (let* ((num-str (list->string (reverse acc)))
                       (num (string->number num-str)))
                  (if num
                      num
                      (error "parse-json-string" "invalid number format" num-str)))))))

      (define (parse-literal expected-vec expected-str value)
        (let ((len (vector-length expected-vec)))
          (let loop ((i 0))
            (if (< i len)
                (let ((c (next)))
                  (if (and (not (eof-object? c))
                           (char=? c (vector-ref expected-vec i)))
                      (loop (+ i 1))
                      (error "parse-json-string" (string-append "invalid literal, expected '" expected-str "'"))))
                value))))

      (define (parse-array)
        (let ((open-c (next)))
          (if (not (char=? open-c #\[))
              (error "parse-json-string" "array must begin with '['" open-c)))
        (skip-whitespace)
        (let ((c (peek)))
          (if (eof-object? c)
              (error "parse-json-string" "unexpected EOF in array")
              (if (char=? c #\])
                  (begin
                    (next) ; consume #\]
                    '#())
                  (let loop ((acc '()))
                    (let ((val (parse-val)))
                      (skip-whitespace)
                      (let ((next-c (next)))
                        (cond
                          ((eof-object? next-c)
                           (error "parse-json-string" "unexpected EOF in array"))
                          ((char=? next-c #\])
                           (list->vector (reverse (cons val acc))))
                          ((char=? next-c #\,)
                           (loop (cons val acc)))
                          (else
                           (error "parse-json-string" "expected ',' or ']'" next-c))))))))))

      (define (parse-object)
        (let ((open-c (next)))
          (if (not (char=? open-c #\{))
              (error "parse-json-string" "object must begin with '{'" open-c)))
        (skip-whitespace)
        (let ((c (peek)))
          (if (eof-object? c)
              (error "parse-json-string" "unexpected EOF in object")
              (if (char=? c #\})
                  (begin
                    (next) ; consume #\}
                    '())
                  (let loop ((acc '()))
                    (skip-whitespace)
                    (let ((ch (peek)))
                      (if (and (not (eof-object? ch)) (char=? ch #\"))
                          (let ((key (parse-string)))
                            (skip-whitespace)
                            (let ((colon-c (next)))
                              (if (and (not (eof-object? colon-c)) (char=? colon-c #\:))
                                  (let ((val (parse-val)))
                                    (skip-whitespace)
                                    (let ((next-c (next)))
                                      (cond
                                        ((eof-object? next-c)
                                         (error "parse-json-string" "unexpected EOF in object"))
                                        ((char=? next-c #\})
                                         (reverse (cons (cons key val) acc)))
                                        ((char=? next-c #\,)
                                         (loop (cons (cons key val) acc)))
                                        (else
                                         (error "parse-json-string" "expected ',' or '}'" next-c)))))
                                  (error "parse-json-string" "expected ':' after key" colon-c))))
                          (error "parse-json-string" "expected double quoted key" ch))))))))

      (define (parse-val)
        (skip-whitespace)
        (let ((c (peek)))
          (cond
            ((eof-object? c)
             (error "parse-json-string" "unexpected EOF"))
            ((char=? c #\{)
             (parse-object))
            ((char=? c #\[)
             (parse-array))
            ((char=? c #\")
             (parse-string))
            ((char=? c #\t)
             (parse-literal *true-vec* "true" #t))
            ((char=? c #\f)
             (parse-literal *false-vec* "false" #f))
            ((char=? c #\n)
             (parse-literal *null-vec* "null" '()))
            ((or (char=? c #\-)
                 (and (char>=? c #\0) (char<=? c #\9)))
             (parse-number))
            (else
             (error "parse-json-string" "unexpected character" c)))))

      (let ((val (parse-val)))
        (skip-whitespace)
        (let ((final-c (peek)))
          (if (eof-object? final-c)
              val
              (error "parse-json-string" "unexpected characters at end of input" final-c))))))

) ;[end]
