(import (core) (test-lite))

(display "(digamma concurrent) testing\n\n")

(test-begin "async")
(test-eval! (import (core) (digamma concurrent)))
(test-eval! (define (ack m n)
              (cond ((= m 0) (+ n 1))
                    ((= n 0) (ack (- m 1) 1))
                    (else (ack (- m 1) (ack m (- n 1)))))))
(test-eval! (define (fib n)
              (if (< n 2)
                n
                (+ (fib (- n 1))
                  (fib (- n 2))))))
(test-eval! (define a1 (let* ((arg1 (async 2))
                              (arg2 (async 9))
                              (n (async (ack (await arg1) (await arg2))))
                              (a (async (fib (await n)))))
                          (await a))))
(test-equal "inter level await/async" a1 => 10946)
(test-end)
