# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/digamma/github/digamma

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/digamma/github/digamma

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/digamma/github/digamma/CMakeFiles /home/digamma/github/digamma//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/digamma/github/digamma/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named intrinsics_gen

# Build rule for target.
intrinsics_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 intrinsics_gen
.PHONY : intrinsics_gen

# fast build rule for target.
intrinsics_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intrinsics_gen.dir/build.make CMakeFiles/intrinsics_gen.dir/build
.PHONY : intrinsics_gen/fast

#=============================================================================
# Target rules for targets named omp_gen

# Build rule for target.
omp_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 omp_gen
.PHONY : omp_gen

# fast build rule for target.
omp_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omp_gen.dir/build.make CMakeFiles/omp_gen.dir/build
.PHONY : omp_gen/fast

#=============================================================================
# Target rules for targets named acc_gen

# Build rule for target.
acc_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acc_gen
.PHONY : acc_gen

# fast build rule for target.
acc_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acc_gen.dir/build.make CMakeFiles/acc_gen.dir/build
.PHONY : acc_gen/fast

#=============================================================================
# Target rules for targets named ARMTargetParserTableGen

# Build rule for target.
ARMTargetParserTableGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ARMTargetParserTableGen
.PHONY : ARMTargetParserTableGen

# fast build rule for target.
ARMTargetParserTableGen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ARMTargetParserTableGen.dir/build.make CMakeFiles/ARMTargetParserTableGen.dir/build
.PHONY : ARMTargetParserTableGen/fast

#=============================================================================
# Target rules for targets named AArch64TargetParserTableGen

# Build rule for target.
AArch64TargetParserTableGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AArch64TargetParserTableGen
.PHONY : AArch64TargetParserTableGen

# fast build rule for target.
AArch64TargetParserTableGen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AArch64TargetParserTableGen.dir/build.make CMakeFiles/AArch64TargetParserTableGen.dir/build
.PHONY : AArch64TargetParserTableGen/fast

#=============================================================================
# Target rules for targets named RISCVTargetParserTableGen

# Build rule for target.
RISCVTargetParserTableGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RISCVTargetParserTableGen
.PHONY : RISCVTargetParserTableGen

# fast build rule for target.
RISCVTargetParserTableGen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RISCVTargetParserTableGen.dir/build.make CMakeFiles/RISCVTargetParserTableGen.dir/build
.PHONY : RISCVTargetParserTableGen/fast

#=============================================================================
# Target rules for targets named nanos_core

# Build rule for target.
nanos_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nanos_core
.PHONY : nanos_core

# fast build rule for target.
nanos_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/build
.PHONY : nanos_core/fast

#=============================================================================
# Target rules for targets named nanos_io

# Build rule for target.
nanos_io: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nanos_io
.PHONY : nanos_io

# fast build rule for target.
nanos_io/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_io.dir/build.make CMakeFiles/nanos_io.dir/build
.PHONY : nanos_io/fast

#=============================================================================
# Target rules for targets named nanos

# Build rule for target.
nanos: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nanos
.PHONY : nanos

# fast build rule for target.
nanos/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos.dir/build.make CMakeFiles/nanos.dir/build
.PHONY : nanos/fast

#=============================================================================
# Target rules for targets named test_object

# Build rule for target.
test_object: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_object
.PHONY : test_object

# fast build rule for target.
test_object/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_object.dir/build.make CMakeFiles/test_object.dir/build
.PHONY : test_object/fast

#=============================================================================
# Target rules for targets named test_gc

# Build rule for target.
test_gc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_gc
.PHONY : test_gc

# fast build rule for target.
test_gc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_gc.dir/build.make CMakeFiles/test_gc.dir/build
.PHONY : test_gc/fast

#=============================================================================
# Target rules for targets named test_printer

# Build rule for target.
test_printer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_printer
.PHONY : test_printer

# fast build rule for target.
test_printer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_printer.dir/build.make CMakeFiles/test_printer.dir/build
.PHONY : test_printer/fast

#=============================================================================
# Target rules for targets named test_printer_printf

# Build rule for target.
test_printer_printf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_printer_printf
.PHONY : test_printer_printf

# fast build rule for target.
test_printer_printf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_printer_printf.dir/build.make CMakeFiles/test_printer_printf.dir/build
.PHONY : test_printer_printf/fast

#=============================================================================
# Target rules for targets named test_reader

# Build rule for target.
test_reader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_reader
.PHONY : test_reader

# fast build rule for target.
test_reader/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_reader.dir/build.make CMakeFiles/test_reader.dir/build
.PHONY : test_reader/fast

#=============================================================================
# Target rules for targets named test_r7rs

# Build rule for target.
test_r7rs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_r7rs
.PHONY : test_r7rs

# fast build rule for target.
test_r7rs/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_r7rs.dir/build.make CMakeFiles/test_r7rs.dir/build
.PHONY : test_r7rs/fast

#=============================================================================
# Target rules for targets named test_radix

# Build rule for target.
test_radix: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_radix
.PHONY : test_radix

# fast build rule for target.
test_radix/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/build
.PHONY : test_radix/fast

#=============================================================================
# Target rules for targets named test_hash

# Build rule for target.
test_hash: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_hash
.PHONY : test_hash

# fast build rule for target.
test_hash/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_hash.dir/build.make CMakeFiles/test_hash.dir/build
.PHONY : test_hash/fast

#=============================================================================
# Target rules for targets named test_symbol

# Build rule for target.
test_symbol: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_symbol
.PHONY : test_symbol

# fast build rule for target.
test_symbol/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_symbol.dir/build.make CMakeFiles/test_symbol.dir/build
.PHONY : test_symbol/fast

#=============================================================================
# Target rules for targets named test_closure_analysis

# Build rule for target.
test_closure_analysis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_closure_analysis
.PHONY : test_closure_analysis

# fast build rule for target.
test_closure_analysis/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_closure_analysis.dir/build.make CMakeFiles/test_closure_analysis.dir/build
.PHONY : test_closure_analysis/fast

#=============================================================================
# Target rules for targets named test_codegen

# Build rule for target.
test_codegen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_codegen
.PHONY : test_codegen

# fast build rule for target.
test_codegen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_codegen.dir/build.make CMakeFiles/test_codegen.dir/build
.PHONY : test_codegen/fast

#=============================================================================
# Target rules for targets named repro_apply

# Build rule for target.
repro_apply: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 repro_apply
.PHONY : repro_apply

# fast build rule for target.
repro_apply/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/repro_apply.dir/build.make CMakeFiles/repro_apply.dir/build
.PHONY : repro_apply/fast

src/arch_arm64.o: src/arch_arm64.cpp.o
.PHONY : src/arch_arm64.o

# target to build an object file
src/arch_arm64.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/arch_arm64.cpp.o
.PHONY : src/arch_arm64.cpp.o

src/arch_arm64.i: src/arch_arm64.cpp.i
.PHONY : src/arch_arm64.i

# target to preprocess a source file
src/arch_arm64.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/arch_arm64.cpp.i
.PHONY : src/arch_arm64.cpp.i

src/arch_arm64.s: src/arch_arm64.cpp.s
.PHONY : src/arch_arm64.s

# target to generate assembly for a file
src/arch_arm64.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/arch_arm64.cpp.s
.PHONY : src/arch_arm64.cpp.s

src/bit.o: src/bit.cpp.o
.PHONY : src/bit.o

# target to build an object file
src/bit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/bit.cpp.o
.PHONY : src/bit.cpp.o

src/bit.i: src/bit.cpp.i
.PHONY : src/bit.i

# target to preprocess a source file
src/bit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/bit.cpp.i
.PHONY : src/bit.cpp.i

src/bit.s: src/bit.cpp.s
.PHONY : src/bit.s

# target to generate assembly for a file
src/bit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/bit.cpp.s
.PHONY : src/bit.cpp.s

src/codegen.o: src/codegen.cpp.o
.PHONY : src/codegen.o

# target to build an object file
src/codegen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/codegen.cpp.o
.PHONY : src/codegen.cpp.o

src/codegen.i: src/codegen.cpp.i
.PHONY : src/codegen.i

# target to preprocess a source file
src/codegen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/codegen.cpp.i
.PHONY : src/codegen.cpp.i

src/codegen.s: src/codegen.cpp.s
.PHONY : src/codegen.s

# target to generate assembly for a file
src/codegen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/codegen.cpp.s
.PHONY : src/codegen.cpp.s

src/codegen_aux.o: src/codegen_aux.cpp.o
.PHONY : src/codegen_aux.o

# target to build an object file
src/codegen_aux.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/codegen_aux.cpp.o
.PHONY : src/codegen_aux.cpp.o

src/codegen_aux.i: src/codegen_aux.cpp.i
.PHONY : src/codegen_aux.i

# target to preprocess a source file
src/codegen_aux.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/codegen_aux.cpp.i
.PHONY : src/codegen_aux.cpp.i

src/codegen_aux.s: src/codegen_aux.cpp.s
.PHONY : src/codegen_aux.s

# target to generate assembly for a file
src/codegen_aux.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/codegen_aux.cpp.s
.PHONY : src/codegen_aux.cpp.s

src/concurrent_heap.o: src/concurrent_heap.cpp.o
.PHONY : src/concurrent_heap.o

# target to build an object file
src/concurrent_heap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/concurrent_heap.cpp.o
.PHONY : src/concurrent_heap.cpp.o

src/concurrent_heap.i: src/concurrent_heap.cpp.i
.PHONY : src/concurrent_heap.i

# target to preprocess a source file
src/concurrent_heap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/concurrent_heap.cpp.i
.PHONY : src/concurrent_heap.cpp.i

src/concurrent_heap.s: src/concurrent_heap.cpp.s
.PHONY : src/concurrent_heap.s

# target to generate assembly for a file
src/concurrent_heap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/concurrent_heap.cpp.s
.PHONY : src/concurrent_heap.cpp.s

src/concurrent_pool.o: src/concurrent_pool.cpp.o
.PHONY : src/concurrent_pool.o

# target to build an object file
src/concurrent_pool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/concurrent_pool.cpp.o
.PHONY : src/concurrent_pool.cpp.o

src/concurrent_pool.i: src/concurrent_pool.cpp.i
.PHONY : src/concurrent_pool.i

# target to preprocess a source file
src/concurrent_pool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/concurrent_pool.cpp.i
.PHONY : src/concurrent_pool.cpp.i

src/concurrent_pool.s: src/concurrent_pool.cpp.s
.PHONY : src/concurrent_pool.s

# target to generate assembly for a file
src/concurrent_pool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/concurrent_pool.cpp.s
.PHONY : src/concurrent_pool.cpp.s

src/concurrent_slab.o: src/concurrent_slab.cpp.o
.PHONY : src/concurrent_slab.o

# target to build an object file
src/concurrent_slab.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/concurrent_slab.cpp.o
.PHONY : src/concurrent_slab.cpp.o

src/concurrent_slab.i: src/concurrent_slab.cpp.i
.PHONY : src/concurrent_slab.i

# target to preprocess a source file
src/concurrent_slab.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/concurrent_slab.cpp.i
.PHONY : src/concurrent_slab.cpp.i

src/concurrent_slab.s: src/concurrent_slab.cpp.s
.PHONY : src/concurrent_slab.s

# target to generate assembly for a file
src/concurrent_slab.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/concurrent_slab.cpp.s
.PHONY : src/concurrent_slab.cpp.s

src/hash.o: src/hash.cpp.o
.PHONY : src/hash.o

# target to build an object file
src/hash.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/hash.cpp.o
.PHONY : src/hash.cpp.o

src/hash.i: src/hash.cpp.i
.PHONY : src/hash.i

# target to preprocess a source file
src/hash.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/hash.cpp.i
.PHONY : src/hash.cpp.i

src/hash.s: src/hash.cpp.s
.PHONY : src/hash.s

# target to generate assembly for a file
src/hash.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/hash.cpp.s
.PHONY : src/hash.cpp.s

src/nanos.o: src/nanos.cpp.o
.PHONY : src/nanos.o

# target to build an object file
src/nanos.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos.dir/build.make CMakeFiles/nanos.dir/src/nanos.cpp.o
.PHONY : src/nanos.cpp.o

src/nanos.i: src/nanos.cpp.i
.PHONY : src/nanos.i

# target to preprocess a source file
src/nanos.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos.dir/build.make CMakeFiles/nanos.dir/src/nanos.cpp.i
.PHONY : src/nanos.cpp.i

src/nanos.s: src/nanos.cpp.s
.PHONY : src/nanos.s

# target to generate assembly for a file
src/nanos.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos.dir/build.make CMakeFiles/nanos.dir/src/nanos.cpp.s
.PHONY : src/nanos.cpp.s

src/nanos_subr.o: src/nanos_subr.cpp.o
.PHONY : src/nanos_subr.o

# target to build an object file
src/nanos_subr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/nanos_subr.cpp.o
.PHONY : src/nanos_subr.cpp.o

src/nanos_subr.i: src/nanos_subr.cpp.i
.PHONY : src/nanos_subr.i

# target to preprocess a source file
src/nanos_subr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/nanos_subr.cpp.i
.PHONY : src/nanos_subr.cpp.i

src/nanos_subr.s: src/nanos_subr.cpp.s
.PHONY : src/nanos_subr.s

# target to generate assembly for a file
src/nanos_subr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/nanos_subr.cpp.s
.PHONY : src/nanos_subr.cpp.s

src/object.o: src/object.cpp.o
.PHONY : src/object.o

# target to build an object file
src/object.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/object.cpp.o
.PHONY : src/object.cpp.o

src/object.i: src/object.cpp.i
.PHONY : src/object.i

# target to preprocess a source file
src/object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/object.cpp.i
.PHONY : src/object.cpp.i

src/object.s: src/object.cpp.s
.PHONY : src/object.s

# target to generate assembly for a file
src/object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/object.cpp.s
.PHONY : src/object.cpp.s

src/object_heap.o: src/object_heap.cpp.o
.PHONY : src/object_heap.o

# target to build an object file
src/object_heap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/object_heap.cpp.o
.PHONY : src/object_heap.cpp.o

src/object_heap.i: src/object_heap.cpp.i
.PHONY : src/object_heap.i

# target to preprocess a source file
src/object_heap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/object_heap.cpp.i
.PHONY : src/object_heap.cpp.i

src/object_heap.s: src/object_heap.cpp.s
.PHONY : src/object_heap.s

# target to generate assembly for a file
src/object_heap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/object_heap.cpp.s
.PHONY : src/object_heap.cpp.s

src/printer.o: src/printer.cpp.o
.PHONY : src/printer.o

# target to build an object file
src/printer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_io.dir/build.make CMakeFiles/nanos_io.dir/src/printer.cpp.o
.PHONY : src/printer.cpp.o

src/printer.i: src/printer.cpp.i
.PHONY : src/printer.i

# target to preprocess a source file
src/printer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_io.dir/build.make CMakeFiles/nanos_io.dir/src/printer.cpp.i
.PHONY : src/printer.cpp.i

src/printer.s: src/printer.cpp.s
.PHONY : src/printer.s

# target to generate assembly for a file
src/printer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_io.dir/build.make CMakeFiles/nanos_io.dir/src/printer.cpp.s
.PHONY : src/printer.cpp.s

src/reader.o: src/reader.cpp.o
.PHONY : src/reader.o

# target to build an object file
src/reader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_io.dir/build.make CMakeFiles/nanos_io.dir/src/reader.cpp.o
.PHONY : src/reader.cpp.o

src/reader.i: src/reader.cpp.i
.PHONY : src/reader.i

# target to preprocess a source file
src/reader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_io.dir/build.make CMakeFiles/nanos_io.dir/src/reader.cpp.i
.PHONY : src/reader.cpp.i

src/reader.s: src/reader.cpp.s
.PHONY : src/reader.s

# target to generate assembly for a file
src/reader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_io.dir/build.make CMakeFiles/nanos_io.dir/src/reader.cpp.s
.PHONY : src/reader.cpp.s

src/utf8.o: src/utf8.cpp.o
.PHONY : src/utf8.o

# target to build an object file
src/utf8.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/utf8.cpp.o
.PHONY : src/utf8.cpp.o

src/utf8.i: src/utf8.cpp.i
.PHONY : src/utf8.i

# target to preprocess a source file
src/utf8.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/utf8.cpp.i
.PHONY : src/utf8.cpp.i

src/utf8.s: src/utf8.cpp.s
.PHONY : src/utf8.s

# target to generate assembly for a file
src/utf8.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/utf8.cpp.s
.PHONY : src/utf8.cpp.s

src/vector.o: src/vector.cpp.o
.PHONY : src/vector.o

# target to build an object file
src/vector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/vector.cpp.o
.PHONY : src/vector.cpp.o

src/vector.i: src/vector.cpp.i
.PHONY : src/vector.i

# target to preprocess a source file
src/vector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/vector.cpp.i
.PHONY : src/vector.cpp.i

src/vector.s: src/vector.cpp.s
.PHONY : src/vector.s

# target to generate assembly for a file
src/vector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanos_core.dir/build.make CMakeFiles/nanos_core.dir/src/vector.cpp.s
.PHONY : src/vector.cpp.s

tests/repro_apply.o: tests/repro_apply.cpp.o
.PHONY : tests/repro_apply.o

# target to build an object file
tests/repro_apply.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/repro_apply.dir/build.make CMakeFiles/repro_apply.dir/tests/repro_apply.cpp.o
.PHONY : tests/repro_apply.cpp.o

tests/repro_apply.i: tests/repro_apply.cpp.i
.PHONY : tests/repro_apply.i

# target to preprocess a source file
tests/repro_apply.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/repro_apply.dir/build.make CMakeFiles/repro_apply.dir/tests/repro_apply.cpp.i
.PHONY : tests/repro_apply.cpp.i

tests/repro_apply.s: tests/repro_apply.cpp.s
.PHONY : tests/repro_apply.s

# target to generate assembly for a file
tests/repro_apply.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/repro_apply.dir/build.make CMakeFiles/repro_apply.dir/tests/repro_apply.cpp.s
.PHONY : tests/repro_apply.cpp.s

tests/test_closure_analysis.o: tests/test_closure_analysis.cpp.o
.PHONY : tests/test_closure_analysis.o

# target to build an object file
tests/test_closure_analysis.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_closure_analysis.dir/build.make CMakeFiles/test_closure_analysis.dir/tests/test_closure_analysis.cpp.o
.PHONY : tests/test_closure_analysis.cpp.o

tests/test_closure_analysis.i: tests/test_closure_analysis.cpp.i
.PHONY : tests/test_closure_analysis.i

# target to preprocess a source file
tests/test_closure_analysis.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_closure_analysis.dir/build.make CMakeFiles/test_closure_analysis.dir/tests/test_closure_analysis.cpp.i
.PHONY : tests/test_closure_analysis.cpp.i

tests/test_closure_analysis.s: tests/test_closure_analysis.cpp.s
.PHONY : tests/test_closure_analysis.s

# target to generate assembly for a file
tests/test_closure_analysis.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_closure_analysis.dir/build.make CMakeFiles/test_closure_analysis.dir/tests/test_closure_analysis.cpp.s
.PHONY : tests/test_closure_analysis.cpp.s

tests/test_codegen.o: tests/test_codegen.cpp.o
.PHONY : tests/test_codegen.o

# target to build an object file
tests/test_codegen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_codegen.dir/build.make CMakeFiles/test_codegen.dir/tests/test_codegen.cpp.o
.PHONY : tests/test_codegen.cpp.o

tests/test_codegen.i: tests/test_codegen.cpp.i
.PHONY : tests/test_codegen.i

# target to preprocess a source file
tests/test_codegen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_codegen.dir/build.make CMakeFiles/test_codegen.dir/tests/test_codegen.cpp.i
.PHONY : tests/test_codegen.cpp.i

tests/test_codegen.s: tests/test_codegen.cpp.s
.PHONY : tests/test_codegen.s

# target to generate assembly for a file
tests/test_codegen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_codegen.dir/build.make CMakeFiles/test_codegen.dir/tests/test_codegen.cpp.s
.PHONY : tests/test_codegen.cpp.s

tests/test_gc.o: tests/test_gc.cpp.o
.PHONY : tests/test_gc.o

# target to build an object file
tests/test_gc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_gc.dir/build.make CMakeFiles/test_gc.dir/tests/test_gc.cpp.o
.PHONY : tests/test_gc.cpp.o

tests/test_gc.i: tests/test_gc.cpp.i
.PHONY : tests/test_gc.i

# target to preprocess a source file
tests/test_gc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_gc.dir/build.make CMakeFiles/test_gc.dir/tests/test_gc.cpp.i
.PHONY : tests/test_gc.cpp.i

tests/test_gc.s: tests/test_gc.cpp.s
.PHONY : tests/test_gc.s

# target to generate assembly for a file
tests/test_gc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_gc.dir/build.make CMakeFiles/test_gc.dir/tests/test_gc.cpp.s
.PHONY : tests/test_gc.cpp.s

tests/test_hash.o: tests/test_hash.cpp.o
.PHONY : tests/test_hash.o

# target to build an object file
tests/test_hash.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_hash.dir/build.make CMakeFiles/test_hash.dir/tests/test_hash.cpp.o
.PHONY : tests/test_hash.cpp.o

tests/test_hash.i: tests/test_hash.cpp.i
.PHONY : tests/test_hash.i

# target to preprocess a source file
tests/test_hash.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_hash.dir/build.make CMakeFiles/test_hash.dir/tests/test_hash.cpp.i
.PHONY : tests/test_hash.cpp.i

tests/test_hash.s: tests/test_hash.cpp.s
.PHONY : tests/test_hash.s

# target to generate assembly for a file
tests/test_hash.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_hash.dir/build.make CMakeFiles/test_hash.dir/tests/test_hash.cpp.s
.PHONY : tests/test_hash.cpp.s

tests/test_object.o: tests/test_object.cpp.o
.PHONY : tests/test_object.o

# target to build an object file
tests/test_object.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_object.dir/build.make CMakeFiles/test_object.dir/tests/test_object.cpp.o
.PHONY : tests/test_object.cpp.o

tests/test_object.i: tests/test_object.cpp.i
.PHONY : tests/test_object.i

# target to preprocess a source file
tests/test_object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_object.dir/build.make CMakeFiles/test_object.dir/tests/test_object.cpp.i
.PHONY : tests/test_object.cpp.i

tests/test_object.s: tests/test_object.cpp.s
.PHONY : tests/test_object.s

# target to generate assembly for a file
tests/test_object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_object.dir/build.make CMakeFiles/test_object.dir/tests/test_object.cpp.s
.PHONY : tests/test_object.cpp.s

tests/test_printer.o: tests/test_printer.cpp.o
.PHONY : tests/test_printer.o

# target to build an object file
tests/test_printer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_printer.dir/build.make CMakeFiles/test_printer.dir/tests/test_printer.cpp.o
.PHONY : tests/test_printer.cpp.o

tests/test_printer.i: tests/test_printer.cpp.i
.PHONY : tests/test_printer.i

# target to preprocess a source file
tests/test_printer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_printer.dir/build.make CMakeFiles/test_printer.dir/tests/test_printer.cpp.i
.PHONY : tests/test_printer.cpp.i

tests/test_printer.s: tests/test_printer.cpp.s
.PHONY : tests/test_printer.s

# target to generate assembly for a file
tests/test_printer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_printer.dir/build.make CMakeFiles/test_printer.dir/tests/test_printer.cpp.s
.PHONY : tests/test_printer.cpp.s

tests/test_printer_printf.o: tests/test_printer_printf.cpp.o
.PHONY : tests/test_printer_printf.o

# target to build an object file
tests/test_printer_printf.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_printer_printf.dir/build.make CMakeFiles/test_printer_printf.dir/tests/test_printer_printf.cpp.o
.PHONY : tests/test_printer_printf.cpp.o

tests/test_printer_printf.i: tests/test_printer_printf.cpp.i
.PHONY : tests/test_printer_printf.i

# target to preprocess a source file
tests/test_printer_printf.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_printer_printf.dir/build.make CMakeFiles/test_printer_printf.dir/tests/test_printer_printf.cpp.i
.PHONY : tests/test_printer_printf.cpp.i

tests/test_printer_printf.s: tests/test_printer_printf.cpp.s
.PHONY : tests/test_printer_printf.s

# target to generate assembly for a file
tests/test_printer_printf.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_printer_printf.dir/build.make CMakeFiles/test_printer_printf.dir/tests/test_printer_printf.cpp.s
.PHONY : tests/test_printer_printf.cpp.s

tests/test_r7rs.o: tests/test_r7rs.cpp.o
.PHONY : tests/test_r7rs.o

# target to build an object file
tests/test_r7rs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_r7rs.dir/build.make CMakeFiles/test_r7rs.dir/tests/test_r7rs.cpp.o
.PHONY : tests/test_r7rs.cpp.o

tests/test_r7rs.i: tests/test_r7rs.cpp.i
.PHONY : tests/test_r7rs.i

# target to preprocess a source file
tests/test_r7rs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_r7rs.dir/build.make CMakeFiles/test_r7rs.dir/tests/test_r7rs.cpp.i
.PHONY : tests/test_r7rs.cpp.i

tests/test_r7rs.s: tests/test_r7rs.cpp.s
.PHONY : tests/test_r7rs.s

# target to generate assembly for a file
tests/test_r7rs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_r7rs.dir/build.make CMakeFiles/test_r7rs.dir/tests/test_r7rs.cpp.s
.PHONY : tests/test_r7rs.cpp.s

tests/test_radix.o: tests/test_radix.cpp.o
.PHONY : tests/test_radix.o

# target to build an object file
tests/test_radix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/tests/test_radix.cpp.o
.PHONY : tests/test_radix.cpp.o

tests/test_radix.i: tests/test_radix.cpp.i
.PHONY : tests/test_radix.i

# target to preprocess a source file
tests/test_radix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/tests/test_radix.cpp.i
.PHONY : tests/test_radix.cpp.i

tests/test_radix.s: tests/test_radix.cpp.s
.PHONY : tests/test_radix.s

# target to generate assembly for a file
tests/test_radix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_radix.dir/build.make CMakeFiles/test_radix.dir/tests/test_radix.cpp.s
.PHONY : tests/test_radix.cpp.s

tests/test_reader.o: tests/test_reader.cpp.o
.PHONY : tests/test_reader.o

# target to build an object file
tests/test_reader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_reader.dir/build.make CMakeFiles/test_reader.dir/tests/test_reader.cpp.o
.PHONY : tests/test_reader.cpp.o

tests/test_reader.i: tests/test_reader.cpp.i
.PHONY : tests/test_reader.i

# target to preprocess a source file
tests/test_reader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_reader.dir/build.make CMakeFiles/test_reader.dir/tests/test_reader.cpp.i
.PHONY : tests/test_reader.cpp.i

tests/test_reader.s: tests/test_reader.cpp.s
.PHONY : tests/test_reader.s

# target to generate assembly for a file
tests/test_reader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_reader.dir/build.make CMakeFiles/test_reader.dir/tests/test_reader.cpp.s
.PHONY : tests/test_reader.cpp.s

tests/test_symbol.o: tests/test_symbol.cpp.o
.PHONY : tests/test_symbol.o

# target to build an object file
tests/test_symbol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_symbol.dir/build.make CMakeFiles/test_symbol.dir/tests/test_symbol.cpp.o
.PHONY : tests/test_symbol.cpp.o

tests/test_symbol.i: tests/test_symbol.cpp.i
.PHONY : tests/test_symbol.i

# target to preprocess a source file
tests/test_symbol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_symbol.dir/build.make CMakeFiles/test_symbol.dir/tests/test_symbol.cpp.i
.PHONY : tests/test_symbol.cpp.i

tests/test_symbol.s: tests/test_symbol.cpp.s
.PHONY : tests/test_symbol.s

# target to generate assembly for a file
tests/test_symbol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_symbol.dir/build.make CMakeFiles/test_symbol.dir/tests/test_symbol.cpp.s
.PHONY : tests/test_symbol.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... AArch64TargetParserTableGen"
	@echo "... ARMTargetParserTableGen"
	@echo "... RISCVTargetParserTableGen"
	@echo "... acc_gen"
	@echo "... intrinsics_gen"
	@echo "... omp_gen"
	@echo "... nanos"
	@echo "... nanos_core"
	@echo "... nanos_io"
	@echo "... repro_apply"
	@echo "... test_closure_analysis"
	@echo "... test_codegen"
	@echo "... test_gc"
	@echo "... test_hash"
	@echo "... test_object"
	@echo "... test_printer"
	@echo "... test_printer_printf"
	@echo "... test_r7rs"
	@echo "... test_radix"
	@echo "... test_reader"
	@echo "... test_symbol"
	@echo "... src/arch_arm64.o"
	@echo "... src/arch_arm64.i"
	@echo "... src/arch_arm64.s"
	@echo "... src/bit.o"
	@echo "... src/bit.i"
	@echo "... src/bit.s"
	@echo "... src/codegen.o"
	@echo "... src/codegen.i"
	@echo "... src/codegen.s"
	@echo "... src/codegen_aux.o"
	@echo "... src/codegen_aux.i"
	@echo "... src/codegen_aux.s"
	@echo "... src/concurrent_heap.o"
	@echo "... src/concurrent_heap.i"
	@echo "... src/concurrent_heap.s"
	@echo "... src/concurrent_pool.o"
	@echo "... src/concurrent_pool.i"
	@echo "... src/concurrent_pool.s"
	@echo "... src/concurrent_slab.o"
	@echo "... src/concurrent_slab.i"
	@echo "... src/concurrent_slab.s"
	@echo "... src/hash.o"
	@echo "... src/hash.i"
	@echo "... src/hash.s"
	@echo "... src/nanos.o"
	@echo "... src/nanos.i"
	@echo "... src/nanos.s"
	@echo "... src/nanos_subr.o"
	@echo "... src/nanos_subr.i"
	@echo "... src/nanos_subr.s"
	@echo "... src/object.o"
	@echo "... src/object.i"
	@echo "... src/object.s"
	@echo "... src/object_heap.o"
	@echo "... src/object_heap.i"
	@echo "... src/object_heap.s"
	@echo "... src/printer.o"
	@echo "... src/printer.i"
	@echo "... src/printer.s"
	@echo "... src/reader.o"
	@echo "... src/reader.i"
	@echo "... src/reader.s"
	@echo "... src/utf8.o"
	@echo "... src/utf8.i"
	@echo "... src/utf8.s"
	@echo "... src/vector.o"
	@echo "... src/vector.i"
	@echo "... src/vector.s"
	@echo "... tests/repro_apply.o"
	@echo "... tests/repro_apply.i"
	@echo "... tests/repro_apply.s"
	@echo "... tests/test_closure_analysis.o"
	@echo "... tests/test_closure_analysis.i"
	@echo "... tests/test_closure_analysis.s"
	@echo "... tests/test_codegen.o"
	@echo "... tests/test_codegen.i"
	@echo "... tests/test_codegen.s"
	@echo "... tests/test_gc.o"
	@echo "... tests/test_gc.i"
	@echo "... tests/test_gc.s"
	@echo "... tests/test_hash.o"
	@echo "... tests/test_hash.i"
	@echo "... tests/test_hash.s"
	@echo "... tests/test_object.o"
	@echo "... tests/test_object.i"
	@echo "... tests/test_object.s"
	@echo "... tests/test_printer.o"
	@echo "... tests/test_printer.i"
	@echo "... tests/test_printer.s"
	@echo "... tests/test_printer_printf.o"
	@echo "... tests/test_printer_printf.i"
	@echo "... tests/test_printer_printf.s"
	@echo "... tests/test_r7rs.o"
	@echo "... tests/test_r7rs.i"
	@echo "... tests/test_r7rs.s"
	@echo "... tests/test_radix.o"
	@echo "... tests/test_radix.i"
	@echo "... tests/test_radix.s"
	@echo "... tests/test_reader.o"
	@echo "... tests/test_reader.i"
	@echo "... tests/test_reader.s"
	@echo "... tests/test_symbol.o"
	@echo "... tests/test_symbol.i"
	@echo "... tests/test_symbol.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

