(define (for-each func lst)
  (cond ((null? lst) #f)
        (else (func (car lst))
              (for-each func (cdr lst)))))

(define (map proc items)
  (if (null? items)
      '()
      (cons (proc (car items))
            (map proc (cdr items)))))

(define (test expr)
  (let* ((all-code expr) (label-map (make-hash-table 'eq?)) (final-code '()))
    (for-each
      (lambda (inst)
        (newline)
        (display "label-map in level 1: ")
        (display label-map)
        (newline)
        (if (not (eq? (car inst) 'label))
            (let ((resolved
                    (map (lambda (x)
                           (newline)
                           (display "label-map in level 2: ")
                           (display label-map)
                           (newline)
                           (if (and (symbol? x) (hash-table-exists? label-map x))
                               (hash-table-get label-map x)
                               x))
                         inst)))
              (set! final-code (cons (list->vector resolved) final-code)))))
      all-code)
    final-code))

(display (test '((const r0 3) (ret))))
(newline)
