;;; REPL for Research Scheme
;;; Integrates macroexpand, optimizer, compiler, and VM.

;; Load dependencies
;; Components are in different directories and use relative loads.
;; We change directory temporarily to load them correctly.

(define (repl:load-relative dir file)
  (let ((old-env (sys-getcwd)))
    (sys-chdir dir)
    (load (string-append "./" file))
    (sys-chdir old-env)))

(let ((root (sys-getcwd)))
  (repl:load-relative (string-append root "/research/syntax") "macroexpand.scm")
  (repl:load-relative (string-append root "/research/opt") "optimizer.scm")
  (repl:load-relative (string-append root "/research/vm") "vm.scm")
  (repl:load-relative (string-append root "/research/vm") "compiler.scm"))

(define (repl:init-globals vm)
  (let ((globals (vm-globals vm)))
    (hash-table-put! globals '+ +)
    (hash-table-put! globals '- -)
    (hash-table-put! globals '* *)
    (hash-table-put! globals '/ /)
    (hash-table-put! globals '= =)
    (hash-table-put! globals '< <)
    (hash-table-put! globals '> >)
    (hash-table-put! globals '<= <=)
    (hash-table-put! globals '>= >=)
    (hash-table-put! globals 'not not)
    (hash-table-put! globals 'cons cons)
    (hash-table-put! globals 'car car)
    (hash-table-put! globals 'cdr cdr)
    (hash-table-put! globals 'pair? pair?)
    (hash-table-put! globals 'null? null?)
    (hash-table-put! globals 'list list)
    (hash-table-put! globals 'display display)
    (hash-table-put! globals 'write write)
    (hash-table-put! globals 'newline newline)
    (hash-table-put! globals 'eq? eq?)
    (hash-table-put! globals 'equal? equal?)
    (hash-table-put! globals 'length length)
    (hash-table-put! globals 'map map)
    (hash-table-put! globals 'for-each for-each)
    globals))

(define (run-repl)
  (display "Starting Research REPL...\n")
  (let ((vm (vm:init-vm)))
    (repl:init-globals vm)
    
    (let loop ()
      (display "> ")
      (flush)
      (let ((expr (read)))
        (if (eof-object? expr)
            (newline)
            (condition-case
             (let* ((expanded (macroexpand expr))
                    (optimized (op:optimize expanded))
                    (code (cp:compile optimized))
                    (ctx (vm:init-context vm code)))
               (let ((result (vm:vm-run ctx)))
                 (write result)
                 (newline)
                 (loop)))
             (e (<error>)
                (display "error: ")
                (display (slot-ref e 'message))
                (newline)
                (loop))))))))

(define (main args)
  (run-repl)
  0)
