;;; REPL for Research Scheme
;;; Integrates macroexpand, optimizer, compiler, and VM.

;; Load dependencies
;; Components are in different directories and use relative loads.
;; We change directory temporarily to load them correctly.

(define (repl:load-relative dir file)
  (let ((old-env (sys-getcwd)))
    (sys-chdir dir)
    (load (string-append "./" file))
    (sys-chdir old-env)))

(let ((root (sys-getcwd)))
  (repl:load-relative (string-append root "/research/syntax") "macroexpand.scm")
  (repl:load-relative (string-append root "/research/opt") "optimizer.scm")
  (repl:load-relative (string-append root "/research/vm") "vm.scm")
  (repl:load-relative (string-append root "/research/vm") "compiler.scm"))

(define (repl:init-globals vm)
  (let ((globals (vm-globals vm)))
    (hash-table-put! globals '+ +)
    (hash-table-put! globals '- -)
    (hash-table-put! globals '* *)
    (hash-table-put! globals '/ /)
    (hash-table-put! globals '= =)
    (hash-table-put! globals '< <)
    (hash-table-put! globals '> >)
    (hash-table-put! globals '<= <=)
    (hash-table-put! globals '>= >=)
    (hash-table-put! globals 'not not)
    (hash-table-put! globals 'cons cons)
    (hash-table-put! globals 'car car)
    (hash-table-put! globals 'cdr cdr)
    (hash-table-put! globals 'pair? pair?)
    (hash-table-put! globals 'null? null?)
    (hash-table-put! globals 'list list)
    (hash-table-put! globals 'display display)
    (hash-table-put! globals 'write write)
    (hash-table-put! globals 'newline newline)
    (hash-table-put! globals 'eq? eq?)
    (hash-table-put! globals 'equal? equal?)
    (hash-table-put! globals 'length length)
    (hash-table-put! globals 'assoc assoc)
    (hash-table-put! globals 'number->string number->string)
    (hash-table-put! globals 'symbol->string symbol->string)
    (hash-table-put! globals 'string->symbol string->symbol)
    (hash-table-put! globals 'string-append string-append)
    (hash-table-put! globals 'set-car! set-car!)
    (hash-table-put! globals 'set-cdr! set-cdr!)
    (hash-table-put! globals 'append append)
    (hash-table-put! globals 'abs abs)
    (hash-table-put! globals 'sqrt sqrt)
    (hash-table-put! globals 'memv memv)
    (hash-table-put! globals 'memq memq)
    (hash-table-put! globals 'reverse reverse)
    (hash-table-put! globals 'eqv? eqv?)
    (hash-table-put! globals 'number? number?)
    (hash-table-put! globals 'vector vector)
    (hash-table-put! globals 'vector-length vector-length)
    (hash-table-put! globals 'vector-ref vector-ref)
    (hash-table-put! globals 'vector-set! vector-set!)
    (hash-table-put! globals 'max max)
    (hash-table-put! globals 'min min)
    (hash-table-put! globals 'symbol? symbol?)
    (hash-table-put! globals 'pair? pair?)
    (hash-table-put! globals 'apply apply)
    (hash-table-put! globals 'cadr cadr)
    (hash-table-put! globals 'caddr caddr)
    (hash-table-put! globals 'cadddr cadddr)
    (hash-table-put! globals 'cddr cddr)
    (hash-table-put! globals 'cdddr cdddr)
    (hash-table-put! globals 'caar caar)
    (hash-table-put! globals 'cdar cdar)
    (hash-table-put! globals 'cadar cadar)
    (hash-table-put! globals 'assq assq)
    (hash-table-put! globals 'filter filter)
    (hash-table-put! globals 'list? list?)
    (hash-table-put! globals 'list->vector list->vector)
    (hash-table-put! globals 'make-hash-table make-hash-table)
    (hash-table-put! globals 'hash-table-put! hash-table-put!)
    (hash-table-put! globals 'hash-table-get hash-table-get)
    (hash-table-put! globals 'hash-table-exists? hash-table-exists?)
    (hash-table-put! globals 'delete delete)
    globals))

(define repl:prelude
  '((define (for-each func lst)
      (cond ((null? lst) #f)
            (else (func (car lst))
                  (for-each func (cdr lst)))))

    (define (map proc items)
      (if (null? items)
          '()
          (cons (proc (car items))
                (map proc (cdr items)))))))

(define (repl:eval-prelude vm)
  (let loop ((exprs repl:prelude))
    (if (null? exprs)
        #t
        (let* ((expanded (macroexpand (car exprs)))
               (optimized (op:optimize expanded))
               (code (cp:compile optimized))
               (ctx (vm:init-context vm code)))
          (vm:vm-run ctx)
          (loop (cdr exprs))))))

(define (run-repl)
  (display "Starting Research REPL...\n")
  (let ((vm (vm:init-vm)))
    (repl:init-globals vm)
    (repl:eval-prelude vm)
    
    (let loop ()
      (display "> ")
      (flush)
      (let ((expr (read)))
        (if (eof-object? expr)
            (newline)
            (with-error-handler
             (lambda (e)
               (display "error: ")
               (display (if (condition? e) (condition-message e) e))
               (newline)
               (loop))
             (lambda ()
               (let* ((expanded (macroexpand expr))
                      (optimized (op:optimize expanded))
                      (code (cp:compile optimized))
                      (ctx (vm:init-context vm code)))
                 (let ((result (vm:vm-run ctx)))
                   (write result)
                   (newline)
                   (loop))))))))))

(define (main args)
  (run-repl)
  0)
