;; copy macro builtins to interaction environment
(copy-environment-macros! (interaction-environment) (current-environment)
  (map car (hashtable->alist (environment-macros (current-environment)))))

;; copy core variables to interaction environment
#;(copy-environment-variables! (interaction-environment) (current-environment)
  (map car (hashtable->alist (environment-variables (current-environment)))))

;(newline)
;(map (lambda (k) (write (car k)) (newline)) (hashtable->alist (environment-variables (current-environment))))
;(newline)

; [To agent] [Case 1] This causes error.
(copy-environment-variables! (interaction-environment) (current-environment)
'(
*
+
-
/
<
<=
=
>
>=
analyze-free-vars-compiler
analyze-free-vars-optimizer
analyze-max-outgoing-args
analyze-mutated-vars-compiler
analyze-mutated-vars-optimizer
analyze-params
analyze-pattern
analyze-used-vars
analyze-variable-usage
any
any?
append
apply
apply-import-spec
apply-syntax-rules
assertion-violation
assoc
assq
assv
boolean?
bound-identifier=?
caaaaar
caaaadr
caaaar
caaadar
caaaddr
caaadr
caaar
caadaar
caadadr
caadar
caaddar
caadddr
caaddr
caadr
caar
cadaaar
cadaadr
cadaar
cadadar
cadaddr
cadadr
cadar
caddaar
caddadr
caddar
cadddar
caddddr
cadddr
caddr
cadr
call/cc
call/ec
call-transformer
call-with-current-continuation
call-with-values
car
cdaaaar
cdaaadr
cdaaar
cdaadar
cdaaddr
cdaadr
cdaar
cdadaar
cdadadr
cdadar
cdaddar
cdadddr
cdaddr
cdadr
cdar
cddaaar
cddaadr
cddaar
cddadar
cddaddr
cddadr
cddar
cdddaar
cdddadr
cdddar
cddddar
cdddddr
cddddr
cdddr
cddr
cdr
char=?
char?
char-numeric?
codegen
codegen-and-run
codegen-application
codegen-args
codegen-if
codegen-lambda
codegen-let
codegen-set!
codegen-symbol
collect
collect-pattern-vars
compile
compile-to-coreform
compiler-ctx-add-closure!
compiler-ctx-all-closures
compiler-ctx-code
compiler-ctx-emit!
compiler-ctx-inc-closure-labels!
compiler-ctx-inc-labels!
compiler-ctx-mutated
compiler-ctx-set-code!
compute-score
cons
cons*
continuation?
copy-environment-macros!
copy-environment-variables!
core-eval
core-form?
count-pair
*cp0-effort-limit*
*cp0-score-limit*
*current-context*
current-environment
*current-syntax-bindings*
*current-syntax-meta-env*
datum->syntax
delete
display
drop
drop-elements
drop-last-cdr
drop-last-n-pair
drop-last-pair
dynamic-wind
environment-macro-contains?
environment-macro-ref
environment-macros
environment-macro-set!
environment-variable-contains?
environment-variable-ref
environment-variables
environment-variable-set!
eq?
equal?
equal-hash
eqv?
error
eval-module-body
eval-transformer-expr
every
every?
exact?
exit
expand
expand-and
expand-begin
expand-case
expand-cond
expand-define
expand-define-module
expand-define-syntax
expand-if
expand-import-module
expand-lambda
expand-let
expand-let*
expand-letrec*
expand-letrec-syntax
expand-let*-syntax
expand-let-syntax
expand-or
expand-qq.9_8a9c92f4-f170-485c-9c4d-ee263e949cd4
expand-qq-list.8_759e4de2-26f7-46a8-8cfa-74034b585bf6
expand-qq-list-splicing.7_d190dea9-900f-47ed-b5e2-e9700a9fd047
expand-quasiquote
expand-quasiquote-form
expand-quote
expand-set!
expand-syntax
expand-syntax-case
expand-template
expand-with-syntax
extract-library-name
extract-macro-defs
extract-module-defined-ids
extract-quasisyntax
filter
filter-runtime-forms
fixnum?
flatten-begins
flatten-params
flatten-params-ll
flatten-params-opt
fold
for-each
for-each-1.4_fabd2cdd-7ebf-4d01-b31e-409e34c97798
for-each-n.5_c3776de9-a326-4063-b496-83465a34948a
free-identifier=?
fresh-mark
fresh-suffix
generate-lifted-name
generate-temporaries
generate-temporary-symbol
gen-label
gensym
get-identifier-context
get-param-names
global-env
has-effects?
hashtable?
hashtable->alist
hashtable-clear!
hashtable-contains?
hashtable-delete!
hashtable-entries
hashtable-ref
hashtable-set!
identifier?
inexact?
infinite?
inject-binding!
*inlining-depth*
inst-arg1
inst-arg2
inst-op
integer?
interaction-environment
internal-define->binding
intersect-ll
iota
is-quasiquote?.4_b80f6a08-f151-42f8-b91b-896b4f7f804b
is-unquote?.2_9a4c0af6-d19b-41e9-ba0c-691a3ff06ad5
is-unquote-splicing?.3_404a7d96-3381-4855-ab2f-0a581b6e2a52
lambda-lift
last-cdr
last-n-pair
last-pair
length
list
list?
list-head
list-ref
list-tail
list-transpose
list-transpose+
list->vector
lookup
lookup-builtin-handler
lookup-macro
lookup-module
loop.2_1b7d33f3-fdae-414a-baa4-93b5b77bf737
loop.24_861555ad-83b8-4def-afe7-dcb4070f2217
loop.2_4940f7b3-9138-47a8-965c-9613ea5b9e82
loop.2_4df498b0-e2b8-4a3c-891c-df99b7268af2
loop.28_38f3eafe-7fcf-4919-9583-c9cf2e5e6a27
loop.29_0eaa168d-3c24-4d58-a897-e9c959e2414a
loop.2_9621f358-d43e-4513-adb9-4174539f6149
loop.2_99feadc9-eba0-4f97-b806-82ba28f21627
loop.2_a4d184b4-30ae-427c-b533-58bc27f49afb
loop.2_b4733f35-3b02-46ed-97a1-0c2e5575749d
loop.2_bbf9e64b-842b-431c-bb57-e9b9f89c5eb8
loop.2_e01dc948-02fb-4068-92d3-e781fe74298e
loop.2_e72058f5-6087-4f27-b7cf-e05b1720e45d
loop.3_213d099d-e558-47bd-a191-19a6af805ffd
loop.3_3efe4658-632a-407f-92e9-b0fa927c237f
loop.3_908a357f-edf4-48d5-944c-c7c99aaf8baa
macro-binding?
macroexpand
macroexpand-1
make-compiler-context
make-environment
make-eq-hashtable
make-equal-hashtable
make-eqv-hashtable
make-macro-binding
make-parameter
make-reg
make-seq
make-syntax-object
make-syntax-rules-transformer
make-variable-transformer
make-vector
mangle-name
map
map-1.4_573f4ddf-a3e1-4179-b7ec-12a7b5e1d5ce
map-improper
map-n.5_7da8d397-6a22-48a4-9d60-46070c76962d
*mark-counter*
match-ellipsis
match-pattern
max
member
memq
memv
min
module-name->string
*modules*
move-args
nan?
newline
no-splicing?.5_c5f5ccbe-0683-4a90-89c5-7253f66a4435
not
null?
number?
number->string
ops-loads
ops-memory-pairs
opt-app
opt-begin
opt-if
optimize
optimize-inner
optimize-once
opt-lambda
opt-let
opt-let-inner
pair?
parameter-proc-0.3_b3c28d56-0690-442e-9b97-44b1478934fe
parameter-proc-1.4_d86cf76b-a8a9-407f-ad50-b011d4abaac1
parse-transformer
partition
perform-inlining
prepare-eval-expr
procedure?
process-export-specs
process-import-set
proper-list?
pure-primitives
real?
reconstruct-params
register-module!
register-renamed!
remove-from-list
*rename-env*
rename-symbol
resolve-core-form
resolve-identifier
resolve-variable
reverse
safepoint
safe-to-inline-val?
set-car!
set-cdr!
set-minus
set-union
should-inline?
small-procedure?
split-internal-defines
string=?
string?
string-append
string-join
string-length
string->number
string-ref
string->symbol
strip-renames
strip-suffix
substitute
substitute-many
substitute-proc
substring
*suffix-counter*
symbol?
symbol->string
syntax-case-match
syntax->datum
syntax-depth-map
syntax->list
syntax-object?
syntax-object-context
syntax-object-datum
*syntax-temp-counter*
syntax-violation
system-environment
take
take-elements
*temp-value*
transpose-matches
try-drop-lambda
undefined
undefined?
unique
unquote-tail?.6_8d0c4794-a075-4525-b09d-4fadbf2be7e0
unrename-core
unspecified
unspecified?
unwrap-env
unwrap-macro-binding
uuid
values
variable-transformer?
variable-transformer-procedure
vector
vector?
vector-length
vector->list
vector-ref
vector-set!
write
))

; [To agent] [Case 2] This do NOT cause error.
#;(define core-variable-list '(
write
vector-set!
vector-ref
vector->list
vector-length
vector?
vector
variable-transformer-procedure
variable-transformer?
values
uuid
unwrap-macro-binding
unwrap-env
unspecified?
unspecified
unrename-core
unquote-tail?.6_8d0c4794-a075-4525-b09d-4fadbf2be7e0
unique
undefined?
undefined
try-drop-lambda
transpose-matches
*temp-value*
take-elements
take
system-environment
syntax-violation
*syntax-temp-counter*
syntax-object-datum
syntax-object-context
syntax-object?
syntax->list
syntax-depth-map
syntax->datum
syntax-case-match
symbol->string
symbol?
*suffix-counter*
substring
substitute-proc
substitute-many
substitute
strip-suffix
strip-renames
string->symbol
string-ref
string->number
string-length
string-join
string-append
string?
string=?
split-internal-defines
small-procedure?
should-inline?
set-union
set-minus
set-cdr!
set-car!
safe-to-inline-val?
safepoint
reverse
resolve-variable
resolve-identifier
resolve-core-form
rename-symbol
*rename-env*
remove-from-list
register-renamed!
register-module!
reconstruct-params
real?
pure-primitives
proper-list?
process-import-set
process-export-specs
procedure?
prepare-eval-expr
perform-inlining
partition
parse-transformer
parameter-proc-1.4_d86cf76b-a8a9-407f-ad50-b011d4abaac1
parameter-proc-0.3_b3c28d56-0690-442e-9b97-44b1478934fe
pair?
opt-let-inner
opt-let
opt-lambda
optimize-once
optimize-inner
optimize
opt-if
opt-begin
opt-app
ops-memory-pairs
ops-loads
number->string
number?
null?
not
no-splicing?.5_c5f5ccbe-0683-4a90-89c5-7253f66a4435
newline
nan?
move-args
*modules*
module-name->string
min
memv
memq
member
max
match-pattern
match-ellipsis
*mark-counter*
map-n.5_7da8d397-6a22-48a4-9d60-46070c76962d
map-improper
map-1.4_573f4ddf-a3e1-4179-b7ec-12a7b5e1d5ce
map
mangle-name
make-vector
make-variable-transformer
make-syntax-rules-transformer
make-syntax-object
make-seq
make-reg
make-parameter
make-macro-binding
make-eqv-hashtable
make-equal-hashtable
make-eq-hashtable
make-environment
make-compiler-context
macroexpand-1
macroexpand
macro-binding?
loop.3_908a357f-edf4-48d5-944c-c7c99aaf8baa
loop.3_3efe4658-632a-407f-92e9-b0fa927c237f
loop.3_213d099d-e558-47bd-a191-19a6af805ffd
loop.2_e72058f5-6087-4f27-b7cf-e05b1720e45d
loop.2_e01dc948-02fb-4068-92d3-e781fe74298e
loop.2_bbf9e64b-842b-431c-bb57-e9b9f89c5eb8
loop.2_b4733f35-3b02-46ed-97a1-0c2e5575749d
loop.2_a4d184b4-30ae-427c-b533-58bc27f49afb
loop.2_99feadc9-eba0-4f97-b806-82ba28f21627
loop.2_9621f358-d43e-4513-adb9-4174539f6149
loop.29_0eaa168d-3c24-4d58-a897-e9c959e2414a
loop.28_38f3eafe-7fcf-4919-9583-c9cf2e5e6a27
loop.2_4df498b0-e2b8-4a3c-891c-df99b7268af2
loop.2_4940f7b3-9138-47a8-965c-9613ea5b9e82
loop.24_861555ad-83b8-4def-afe7-dcb4070f2217
loop.2_1b7d33f3-fdae-414a-baa4-93b5b77bf737
lookup-module
lookup-macro
lookup-builtin-handler
lookup
list->vector
list-transpose+
list-transpose
list-tail
list-ref
list-head
list?
list
length
last-pair
last-n-pair
last-cdr
lambda-lift
is-unquote-splicing?.3_404a7d96-3381-4855-ab2f-0a581b6e2a52
is-unquote?.2_9a4c0af6-d19b-41e9-ba0c-691a3ff06ad5
is-quasiquote?.4_b80f6a08-f151-42f8-b91b-896b4f7f804b
iota
intersect-ll
internal-define->binding
interaction-environment
integer?
inst-op
inst-arg2
inst-arg1
*inlining-depth*
inject-binding!
infinite?
inexact?
identifier?
hashtable-set!
hashtable-ref
hashtable-entries
hashtable-delete!
hashtable-contains?
hashtable-clear!
hashtable->alist
hashtable?
has-effects?
global-env
get-param-names
get-identifier-context
gensym
gen-label
generate-temporary-symbol
generate-temporaries
generate-lifted-name
fresh-suffix
fresh-mark
free-identifier=?
for-each-n.5_c3776de9-a326-4063-b496-83465a34948a
for-each-1.4_fabd2cdd-7ebf-4d01-b31e-409e34c97798
for-each
fold
flatten-params-opt
flatten-params-ll
flatten-params
flatten-begins
fixnum?
filter-runtime-forms
filter
extract-quasisyntax
extract-module-defined-ids
extract-macro-defs
extract-library-name
expand-with-syntax
expand-template
expand-syntax-case
expand-syntax
expand-set!
expand-quote
expand-quasiquote-form
expand-quasiquote
expand-qq-list-splicing.7_d190dea9-900f-47ed-b5e2-e9700a9fd047
expand-qq-list.8_759e4de2-26f7-46a8-8cfa-74034b585bf6
expand-qq.9_8a9c92f4-f170-485c-9c4d-ee263e949cd4
expand-or
expand-let-syntax
expand-let*-syntax
expand-letrec-syntax
expand-letrec*
expand-let*
expand-let
expand-lambda
expand-import-module
expand-if
expand-define-syntax
expand-define-module
expand-define
expand-cond
expand-case
expand-begin
expand-and
expand
exit
exact?
every?
every
eval-transformer-expr
eval-module-body
error
eqv?
equal-hash
equal?
eq?
environment-variable-set!
environment-variables
environment-variable-ref
environment-variable-contains?
environment-macro-set!
environment-macros
environment-macro-ref
environment-macro-contains?
dynamic-wind
drop-last-pair
drop-last-n-pair
drop-last-cdr
drop-elements
drop
display
delete
datum->syntax
*current-syntax-meta-env*
*current-syntax-bindings*
current-environment
*current-context*
*cp0-score-limit*
*cp0-effort-limit*
count-pair
core-form?
core-eval
copy-environment-variables!
copy-environment-macros!
compile-to-coreform
continuation?
cons*
cons
compute-score
compiler-ctx-set-code!
compiler-ctx-mutated
compiler-ctx-inc-labels!
compiler-ctx-inc-closure-labels!
compiler-ctx-emit!
compiler-ctx-code
compiler-ctx-all-closures
compiler-ctx-add-closure!
compile
collect-pattern-vars
collect
codegen-symbol
codegen-set!
codegen-let
codegen-lambda
codegen-if
codegen-args
codegen-application
codegen-and-run
codegen
char-numeric?
char?
char=?
cdr
cddr
cdddr
cddddr
cdddddr
cddddar
cdddar
cdddadr
cdddaar
cddar
cddadr
cddaddr
cddadar
cddaar
cddaadr
cddaaar
cdar
cdadr
cdaddr
cdadddr
cdaddar
cdadar
cdadadr
cdadaar
cdaar
cdaadr
cdaaddr
cdaadar
cdaaar
cdaaadr
cdaaaar
car
call-with-values
call-with-current-continuation
call-transformer
call/ec
call/cc
cadr
caddr
cadddr
caddddr
cadddar
caddar
caddadr
caddaar
cadar
cadadr
cadaddr
cadadar
cadaar
cadaadr
cadaaar
caar
caadr
caaddr
caadddr
caaddar
caadar
caadadr
caadaar
caaar
caaadr
caaaddr
caaadar
caaaar
caaaadr
caaaaar
bound-identifier=?
boolean?
assv
assq
assoc
assertion-violation
apply-syntax-rules
apply-import-spec
apply
append
any?
any
analyze-variable-usage
analyze-used-vars
analyze-pattern
analyze-params
analyze-mutated-vars-optimizer
analyze-mutated-vars-compiler
analyze-max-outgoing-args
analyze-free-vars-optimizer
analyze-free-vars-compiler
>=
>
=
<=
<
/
-
+
*
))
#;(copy-environment-variables! (interaction-environment) (current-environment)
core-variable-list)


#;(copy-environment-variables! (interaction-environment) (current-environment)
  '(+ - * / = < > <= >=
    cons car cdr caar cdar cadr cddr cadar cddar caddar cdddar caddr cdddr cadddr
    set-car! set-cdr! length list cons*
    list-ref list->vector memq memv member assq assv assoc reverse append
    not boolean? char? eq? equal? eqv? exact? inexact? infinite? integer? fixnum?
    list? null? number? nan? pair? procedure? real? string? symbol? vector?
    undefined unspecified undefined? unspecified?

    vector make-vector vector-length vector-ref vector-set! vector->list

    string-length string-ref string=? string-append substring
    symbol->string string->symbol number->string string->number
    char=? char-numeric? max min

    write display newline

    hashtable? equal-hash make-eq-hashtable make-eqv-hashtable make-equal-hashtable
    hashtable-ref hashtable-set! hashtable-delete! hashtable-contains?
    hashtable-clear! hashtable-entries hashtable->alist

    make-environment copy-environment-variables! copy-environment-macros!
    environment-macros environment-variables current-environment
    environment-macro-set! environment-macro-ref environment-macro-contains?
    environment-variable-set! environment-variable-ref environment-variable-contains?
    interaction-environment system-environment

    values call-with-values collect safepoint gensym uuid exit
    error apply call/ec dynamic-wind continuation?
    call/cc call-with-current-continuation
    
    map for-each filter make-parameter every? any?
    
    macroexpand core-eval expand-syntax-case))

; (current-environment (interaction-environment))
