;;; REPL for Research Scheme
;;; Integrates macroexpand, optimizer, compiler, and VM.

;; Add load paths relative to this script to find dependencies in core/ and meta/.
;; For best results, run from the project root.
(cond-expand
  (gauche
   (add-load-path "." :relative)
   (add-load-path "../core" :relative)
   (define (flush-output-port port) (flush))
   (define (with-exception-handler handler thunk)
     (guard (e (else (handler e)))
       (thunk))))
  (ypsilon
   (add-load-path "./core")
   (add-load-path "./meta"))
  (else))

;; Load dependencies
(load "core.scm")  ; Load core system
(load "vm.scm")            ; Load VM (meta-specific)

(define (repl:init-globals)
  (environment-variable-set! '+ +)
  (environment-variable-set! '- -)
  (environment-variable-set! '* *)
  (environment-variable-set! '/ /)
  (environment-variable-set! '= =)
  (environment-variable-set! '< <)
  (environment-variable-set! '> >)
  (environment-variable-set! '<= <=)
  (environment-variable-set! '>= >=)
  (environment-variable-set! 'not not)
  (environment-variable-set! 'cons cons)
  (environment-variable-set! 'car car)
  (environment-variable-set! 'cdr cdr)
  (environment-variable-set! 'pair? pair?)
  (environment-variable-set! 'null? null?)
  (environment-variable-set! 'list list)
  (environment-variable-set! 'display display)
  (environment-variable-set! 'write write)
  (environment-variable-set! 'newline newline)
  (environment-variable-set! 'eq? eq?)
  (environment-variable-set! 'equal? equal?)
  (environment-variable-set! 'length length)
  (environment-variable-set! 'assoc assoc)
  (environment-variable-set! 'number->string number->string)
  (environment-variable-set! 'symbol->string symbol->string)
  (environment-variable-set! 'string->symbol string->symbol)
  (environment-variable-set! 'string-append string-append)
  (environment-variable-set! 'set-car! set-car!)
  (environment-variable-set! 'set-cdr! set-cdr!)
  (environment-variable-set! 'append append)
  (environment-variable-set! 'abs abs)
  (environment-variable-set! 'sqrt sqrt)
  (environment-variable-set! 'memv memv)
  (environment-variable-set! 'memq memq)
  (environment-variable-set! 'reverse reverse)
  (environment-variable-set! 'eqv? eqv?)
  (environment-variable-set! 'number? number?)
  (environment-variable-set! 'vector vector)
  (environment-variable-set! 'vector-length vector-length)
  (environment-variable-set! 'vector-ref vector-ref)
  (environment-variable-set! 'vector-set! vector-set!)
  (environment-variable-set! 'max max)
  (environment-variable-set! 'min min)
  (environment-variable-set! 'symbol? symbol?)
  (environment-variable-set! 'apply apply)
  (environment-variable-set! 'cadr cadr)
  (environment-variable-set! 'caddr caddr)
  (environment-variable-set! 'cadddr cadddr)
  (environment-variable-set! 'cddr cddr)
  (environment-variable-set! 'cdddr cdddr)
  (environment-variable-set! 'caar caar)
  (environment-variable-set! 'cdar cdar)
  (environment-variable-set! 'cadar cadar)
  (environment-variable-set! 'assq assq)
  (environment-variable-set! 'filter filter)
  (environment-variable-set! 'list? list?)
  (environment-variable-set! 'list->vector list->vector)
  (environment-variable-set! 'make-hashtable make-hashtable)
  (environment-variable-set! 'make-eq-hashtable make-eq-hashtable)
  (environment-variable-set! 'hashtable-set! hashtable-set!)
  (environment-variable-set! 'hashtable-ref hashtable-ref)
  (environment-variable-set! 'hashtable-contains? hashtable-contains?)
  (environment-variable-set! 'hashtable-delete! hashtable-delete!)
  (environment-variable-set! 'call/cc call/cc)
  (environment-variable-set! 'call/1cc call/cc)
  (environment-variable-set! 'values values)
  (environment-variable-set! 'every? every?)
  (environment-variable-set! 'macroexpand macroexpand)

  ; Followings does not work since it calls nanos:closure from native implementation
  ; to work such subrs, need to add own implementation in repl:prelude like map or for-each.
  (environment-variable-set! 'call-with-values call-with-values)
  (environment-variable-set! 'dynamic-wind dynamic-wind)

  #t)

(define repl:prelude
  '((define (for-each func lst)
      (cond ((null? lst) #f)
            (else (func (car lst))
                  (for-each func (cdr lst)))))

    (define (map proc items)
      (if (null? items)
          '()
          (cons (proc (car items))
                (map proc (cdr items)))))))

(define (repl:eval-prelude)
  (let loop ((exprs repl:prelude))
    (if (null? exprs)
        #t
        (let* ((expanded (macroexpand (car exprs)))
               (optimized (optimize expanded))
               (code (compile optimized))
               (bytecode (generate-bytecode code))
               (ctx (vm:init-context bytecode)))
          (vm:vm-run ctx)
          (loop (cdr exprs))))))

(define (run-repl)
  (display "Starting REPL...\n")
  (repl:init-globals)
  (repl:eval-prelude)
  
  (let loop ()
    (display "> ")
    (flush-output-port (current-output-port))
    (let ((expr (read)))
      (if (eof-object? expr)
          (newline)
          (with-exception-handler
           (lambda (e)
             (display "error: ")
             (display (if (condition? e) (condition-message e) e))
             (newline)
             (loop))
           (lambda ()
             (let* ((expanded (macroexpand expr))
                    (optimized (optimize expanded))
                    (lifted (lambda-lift optimized))
                    (code (compile lifted))
                    (bytecode (generate-bytecode code))
                    (ctx (vm:init-context bytecode)))
               (newline)
               (display "macroexpanded form:\n")
               (write expanded)
               (newline)
               (newline)
               (display "optimized form:\n")
               (write optimized)
               (newline)
               (newline)
               (display "lifted form:\n")
               (write lifted)
               (newline)
               (newline)
               (display "compiled code for nanos input:\n")
               (write code)
               (newline)
               (newline)
               (let ((result (vm:vm-run ctx)))
                 (write result)
                 (newline)
                 (loop)))))))))
