(define-module (core)
    (export 
        *
        +
        -
        /
        <
        <=
        =
        >
        >=
        _current-syntax-bindings.145bed32-69c0-4df2-8c06-89f53ab9907f
        _current-syntax-meta-env.145bed32-69c0-4df2-8c06-89f53ab9907f
        _expand-syntax-case.145bed32-69c0-4df2-8c06-89f53ab9907f
        _expand-syntax.145bed32-69c0-4df2-8c06-89f53ab9907f
        _expand-with-syntax.145bed32-69c0-4df2-8c06-89f53ab9907f
        _fresh-suffix.145bed32-69c0-4df2-8c06-89f53ab9907f
        add-load-path
        any
        append
        apply
        assertion-violation
        assoc
        assq
        assv
        boolean?
        bound-identifier=?
        caaaaar
        caaaadr
        caaaar
        caaadar
        caaaddr
        caaadr
        caaar
        caadaar
        caadadr
        caadar
        caaddar
        caadddr
        caaddr
        caadr
        caar
        cadaaar
        cadaadr
        cadaar
        cadadar
        cadaddr
        cadadr
        cadar
        caddaar
        caddadr
        caddar
        cadddar
        caddddr
        cadddr
        caddr
        cadr
        call-with-current-continuation
        call-with-port
        call-with-string-output-port
        call-with-values
        call/cc
        call/ec
        car
        cdaaaar
        cdaaadr
        cdaaar
        cdaadar
        cdaaddr
        cdaadr
        cdaar
        cdadaar
        cdadadr
        cdadar
        cdaddar
        cdadddr
        cdaddr
        cdadr
        cdar
        cddaaar
        cddaadr
        cddaar
        cddadar
        cddaddr
        cddadr
        cddar
        cdddaar
        cdddadr
        cdddar
        cddddar
        cdddddr
        cddddr
        cdddr
        cddr
        cdr
        char-numeric?
        char=?
        char?
        close-port
        collect
        compile
        compile-to-coreform
        cons
        cons*
        continuation?
        copy-environment-macros!
        copy-environment-variables!
        core-eval
        current-environment
        current-error-port
        current-input-port
        current-module-registry
        current-output-port
        cyclic-object?
        datum->syntax
        display
        dynamic-wind
        environment-macro-contains?
        environment-macro-ref
        environment-macro-set!
        environment-macros
        environment-variable-contains?
        environment-variable-ref
        environment-variable-set!
        environment-variables
        eof-object?
        eq?
        equal-hash
        equal?
        eqv?
        error
        every
        exact?
        exit
        file-exists?
        filter
        fixnum?
        flush-output-port
        fold
        for-each
        format
        free-identifier=?
        generate-temporaries
        gensym
        hashtable->alist
        hashtable-clear!
        hashtable-contains?
        hashtable-delete!
        hashtable-entries
        hashtable-ref
        hashtable-set!
        hashtable?
        identifier?
        inexact?
        infinite?
        integer?
        iota
        lambda-lift
        length
        list
        list->vector
        list-head
        list-ref
        list-tail
        list-transpose
        list-transpose+
        list?
        load
        load-module
        lookup-process-environment
        macroexpand
        make-environment
        make-eq-hashtable
        make-equal-hashtable
        make-eqv-hashtable
        make-parameter
        make-variable-transformer
        make-vector
        map
        max
        member
        memq
        memv
        min
        nan?
        newline
        not
        null?
        number->string
        number?
        open-file-input-port
        open-file-output-port
        open-string-output-port
        optimize
        pair?
        partition
        procedure?
        proper-list?
        put-char
        put-string
        read
        real?
        reverse
        safepoint
        scheme-load-paths
        set-car!
        set-cdr!
        standard-error-port
        standard-input-port
        standard-output-port
        string->number
        string->symbol
        string-append
        string-join
        string-length
        string-ref
        string=?
        string?
        substring
        symbol->string
        symbol?
        syntax->datum
        syntax-violation
        system-environment
        undefined
        undefined?
        unique
        unspecified
        unspecified?
        uuid
        values
        vector
        vector->list
        vector-length
        vector-ref
        vector-set!
        vector?
        write
        write-with-shared-structure
        write/ss
    )
)

