;; Copyright (c) 2004-2026 Yoshikatsu Fujita / LittleWing Company Limited.
;; See LICENSE file for terms and conditions of use.

;; Lambda Lifting Pass

(define (flatten-params-ll params)
  (let loop ((p params) (acc '()))
    (cond ((null? p) (reverse acc))
          ((symbol? p) (reverse (cons p acc)))
          ((pair? p) (loop (cdr p) (cons (car p) acc)))
          (else (reverse acc)))))

(define (intersect-ll l1 l2)
  (filter (lambda (x) (memq x l2)) l1))

(define (generate-lifted-name sym)
  (string->symbol
   (string-append (symbol->string sym) "_" (uuid))))

(define (lambda-lift expr)
  (let ((lifted-defs '()))
    (letrec ((walk
              (lambda (e env renames)
                (cond ((symbol? e)
                       (let ((sub (assq e renames)))
                         (if sub (cdr sub) e)))
                      ((not (pair? e)) e)
                      ((eq? (car e) 'quote) e)
                      ((eq? (car e) 'if)
                       `(if ,(walk (cadr e) env renames)
                            ,(walk (caddr e) env renames)
                            ,(if (null? (cdddr e)) ''#f (walk (cadddr e) env renames))))
                      ((eq? (car e) 'begin)
                       `(begin ,@(map (lambda (x) (walk x env renames)) (cdr e))))
                      ((eq? (car e) 'set!)
                       `(set! ,(let ((sub (assq (cadr e) renames))) (if sub (cdr sub) (cadr e)))
                              ,(walk (caddr e) env renames)))
                      ((eq? (car e) 'define)
                       (let ((head (cadr e)))
                         (if (pair? head)
                             `(define ,(car head) ,(walk `(lambda ,(cdr head) ,@(cddr e)) env renames))
                             `(define ,head ,(walk (caddr e) env renames)))))
                      ((eq? (car e) 'lambda)
                       (let* ((params (cadr e))
                              (new-env (append (flatten-params-ll params) env)))
                         `(lambda ,params ,@(map (lambda (x) (walk x new-env renames)) (cddr e)))))
                      ((eq? (car e) 'let)
                       (let* ((bindings (cadr e))
                              (vars (map car bindings))
                              (vals (map cadr bindings))
                              (new-env (append vars env)))
                         (let loop ((b (cddr e)) (sets '()) (rest-body '()))
                           (if (and (pair? b) (pair? (car b)) (eq? (caar b) 'set!)
                                    (memq (cadar b) vars)
                                    (pair? (caddar b)) (eq? (car (caddar b)) 'lambda))
                               (loop (cdr b) (cons (car b) sets) (cdr b))
                               (let* ((sets (reverse sets))
                                      (candidate-vars (map cadr sets))
                                      (candidate-lams (map caddr sets)))
                                 (let fixpoint ((forbidden (append env (set-minus vars candidate-vars)))
                                                (liftable-sets sets))
                                   (let loop ((rest liftable-sets) (new-liftable '()) (new-forbidden forbidden) (changed #f))
                                     (if (pair? rest)
                                         (let* ((s (car rest))
                                                (var (cadr s))
                                                (lam (caddr s))
                                                (fv (analyze-free-vars-optimizer lam '())))
                                           (if (null? (intersect-ll fv forbidden))
                                               (loop (cdr rest) (cons s new-liftable) new-forbidden changed)
                                               (loop (cdr rest) new-liftable (cons var new-forbidden) #t)))
                                         (if changed
                                             (fixpoint new-forbidden (reverse new-liftable))
                                             (let* ((final-liftable (reverse new-liftable))
                                                    (final-not-liftable (filter (lambda (s) (memq (cadr s) new-forbidden)) sets))
                                                    (new-renames
                                                     (append (map (lambda (s)
                                                                    (let ((old-var (cadr s)))
                                                                      (cons old-var (generate-lifted-name old-var))))
                                                                  final-liftable)
                                                             renames)))
                                               (for-each
                                                (lambda (s)
                                                  (let* ((var (cadr s))
                                                         (new-var (cdr (assq var new-renames)))
                                                         (lam (caddr s))
                                                         (walked-lam (walk lam '() new-renames)))
                                                    (set! lifted-defs (cons `(define ,new-var ,walked-lam) lifted-defs))))
                                                final-liftable)
                                             
                                             (let* ((lifted-vars (map cadr final-liftable))
                                                    (residual-sets (map (lambda (s) `(set! ,(cadr s) ,(walk (caddr s) new-env new-renames))) final-not-liftable))
                                                    (residual-body (map (lambda (x) (walk x new-env new-renames)) b))
                                                    (residual-bindings (let loop-bind ((bs bindings))
                                                                         (cond ((null? bs) '())
                                                                               ((memq (caar bs) lifted-vars) (loop-bind (cdr bs)))
                                                                               (else (cons (list (caar bs) (walk (cadar bs) env new-renames)) (loop-bind (cdr bs))))))))
                                               (if (and (null? residual-bindings) (null? residual-sets))
                                                   (if (= (length residual-body) 1)
                                                       (car residual-body)
                                                       `(begin ,@residual-body))
                                                   `(let ,residual-bindings
                                                      ,@residual-sets
                                                      ,@residual-body)))))))))))))
                      (else
                       (map (lambda (x) (walk x env renames)) e))))))
      (let ((new-expr (walk expr '() '())))
        (if (null? lifted-defs)
            new-expr
            `(begin ,@(reverse lifted-defs) ,new-expr))))))
