;; Copyright (c) 2004-2026 Yoshikatsu Fujita / LittleWing Company Limited.
;; See LICENSE file for terms and conditions of use.

;; Lambda Lifting Pass

(define (flatten-params-ll params)
  (cond ((null? params) '())
        ((symbol? params) (list params))
        ((pair? params) (cons (car params) (flatten-params-ll (cdr params))))
        (else '())))

(define (intersect-ll l1 l2)
  (let loop ((l1 l1) (acc '()))
    (cond ((null? l1) (reverse acc))
          ((memq (car l1) l2) (loop (cdr l1) (cons (car l1) acc)))
          (else (loop (cdr l1) acc)))))

(define (lambda-lift expr)
  (let ((lifted-defs '()))
    (letrec ((walk
              (lambda (e env)
                (cond ((symbol? e) e)
                      ((not (pair? e)) e)
                      ((eq? (car e) 'quote) e)
                      ((eq? (car e) 'if)
                       `(if ,(walk (cadr e) env)
                            ,(walk (caddr e) env)
                            ,(if (null? (cdddr e)) ''#f (walk (cadddr e) env))))
                      ((eq? (car e) 'begin)
                       `(begin ,@(map (lambda (x) (walk x env)) (cdr e))))
                      ((eq? (car e) 'set!)
                       `(set! ,(cadr e) ,(walk (caddr e) env)))
                      ((eq? (car e) 'define)
                       (let ((head (cadr e)))
                         (if (pair? head)
                             `(define ,(car head) ,(walk `(lambda ,(cdr head) ,@(cddr e)) env))
                             `(define ,head ,(walk (caddr e) env)))))
                      ((eq? (car e) 'lambda)
                       (let* ((params (cadr e))
                              (new-env (append (flatten-params-ll params) env)))
                         `(lambda ,params ,@(map (lambda (x) (walk x new-env)) (cddr e)))))
                      ((eq? (car e) 'let)
                       (let* ((bindings (cadr e))
                              (vars (map car bindings))
                              (vals (map cadr bindings))
                              (new-env (append vars env)))
                         (let loop ((b (cddr e)) (sets '()) (rest-body '()))
                           (if (and (pair? b) (pair? (car b)) (eq? (caar b) 'set!)
                                    (memq (cadar b) vars)
                                    (pair? (caddar b)) (eq? (car (caddar b)) 'lambda))
                               (loop (cdr b) (cons (car b) sets) (cdr b))
                               (let* ((sets (reverse sets))
                                      (candidate-vars (map cadr sets))
                                      (candidate-lams (map caddr sets)))
                                 (let fixpoint ((forbidden (append env (set-minus vars candidate-vars)))
                                                (liftable-sets sets))
                                   (let* ((new-liftable '())
                                          (new-forbidden forbidden)
                                          (changed #f))
                                     (for-each
                                      (lambda (s)
                                        (let* ((var (cadr s))
                                               (lam (caddr s))
                                               (fv (analyze-free-vars-optimizer lam '())))
                                          (if (null? (intersect-ll fv forbidden))
                                              (set! new-liftable (cons s new-liftable))
                                              (begin
                                                (set! changed #t)
                                                (set! new-forbidden (cons var new-forbidden))))))
                                      liftable-sets)
                                     (if changed
                                         (fixpoint new-forbidden (reverse new-liftable))
                                         (let ((final-liftable (reverse new-liftable))
                                               (final-not-liftable (filter (lambda (s) (memq (cadr s) new-forbidden)) sets)))
                                           
                                           (for-each
                                            (lambda (s)
                                              (let* ((var (cadr s))
                                                     (lam (caddr s))
                                                     (walked-lam (walk lam '())))
                                                (set! lifted-defs (cons `(define ,var ,walked-lam) lifted-defs))))
                                            final-liftable)
                                           
                                           (let* ((lifted-vars (map cadr final-liftable))
                                                  (residual-sets (map (lambda (s) `(set! ,(cadr s) ,(walk (caddr s) new-env))) final-not-liftable))
                                                  (residual-body (map (lambda (x) (walk x new-env)) b))
                                                  (residual-bindings (let loop-bind ((bs bindings))
                                                                       (cond ((null? bs) '())
                                                                             ((memq (caar bs) lifted-vars) (loop-bind (cdr bs)))
                                                                             (else (cons (list (caar bs) (walk (cadar bs) env)) (loop-bind (cdr bs))))))))
                                             (if (and (null? residual-bindings) (null? residual-sets))
                                                 (if (= (length residual-body) 1)
                                                     (car residual-body)
                                                     `(begin ,@residual-body))
                                                 `(let ,residual-bindings
                                                    ,@residual-sets
                                                    ,@residual-body))))))))))))
                      (else
                       (map (lambda (x) (walk x env)) e))))))
      (let ((new-expr (walk expr '())))
        (if (null? lifted-defs)
            new-expr
            `(begin ,@(reverse lifted-defs) ,new-expr))))))
