;; Copyright (c) 2004-2026 Yoshikatsu Fujita / LittleWing Company Limited.
;; See LICENSE file for terms and conditions of use.

;; Lambda Lifting Pass

(define (flatten-params-ll params)
  (let loop ((p params) (acc '()))
    (cond ((null? p) (reverse acc))
          ((symbol? p) (reverse (cons p acc)))
          ((pair? p) (loop (cdr p) (cons (car p) acc)))
          (else (reverse acc)))))

(define (any-in-set? lst ht)
  (let loop ((l lst))
    (and (pair? l)
         (or (hashtable-contains? ht (car l))
             (loop (cdr l))))))

(define (generate-lifted-name sym)
  (string->symbol
   (string-append (symbol->string sym) "_" (uuid))))

(define (lambda-lift expr)
  (let ((lifted-defs '()))
    (letrec ((walk
              (lambda (e env renames)
                (define (lookup var)
                  (let ((sub (assq var renames)))
                    (if sub (cdr sub) var)))

                (define (process-define e)
                  (let ((head (cadr e)) (body (cddr e)))
                    (if (pair? head)
                        `(define ,(car head) ,(walk `(lambda ,(cdr head) ,@body) env renames))
                        `(define ,head ,(walk (caddr e) env renames)))))

                (define (process-lambda e)
                  (let* ((params (cadr e))
                         (body (cddr e))
                         (new-env (append (flatten-params-ll params) env)))
                    `(lambda ,params ,@(map (lambda (x) (walk x new-env renames)) body))))

                (define (process-let e)
                  (let* ((bindings (cadr e))
                         (vars (map car bindings))
                         (vals (map cadr bindings))
                         (body (cddr e))
                         (new-env (append vars env)))
                    (let loop ((b body) (sets '()))
                      (if (and (pair? b) (pair? (car b)) (eq? (caar b) 'set!)
                               (memq (cadar b) vars)
                               (pair? (caddar b)) (eq? (car (caddar b)) 'lambda))
                          (loop (cdr b) (cons (car b) sets))
                          (let* ((sets (reverse sets))
                                 (candidates (map (lambda (s)
                                                    (let ((lam (caddr s)))
                                                      (list (cadr s) lam (analyze-free-vars-optimizer lam '()))))
                                                  sets)))
                            (let fixpoint ((forbidden-ht (let ((ht (make-eq-hashtable)))
                                                           (for-each (lambda (v) (hashtable-set! ht v #t))
                                                                     (append env (remove-from-list vars (map car candidates))))
                                                           ht))
                                           (current-candidates candidates))
                              (let loop-cand ((rest current-candidates) (new-candidates '()) (changed #f))
                                (if (pair? rest)
                                    (let* ((c (car rest)) (var (car c)) (lam (cadr c)) (fv (caddr c)))
                                      (if (not (any-in-set? fv forbidden-ht))
                                          (loop-cand (cdr rest) (cons c new-candidates) changed)
                                          (begin (hashtable-set! forbidden-ht var #t)
                                                 (loop-cand (cdr rest) new-candidates #t))))
                                    (if changed
                                        (fixpoint forbidden-ht (reverse new-candidates))
                                        (let* ((final-liftable (reverse new-candidates))
                                               (liftable-vars (map car final-liftable))
                                               (liftable-ht (make-eq-hashtable))
                                               (_ (for-each (lambda (v) (hashtable-set! liftable-ht v #t)) liftable-vars))
                                               (new-renames (append (map (lambda (var) (cons var (generate-lifted-name var))) liftable-vars) renames)))

                                          (for-each (lambda (c)
                                                      (let* ((var (car c))
                                                             (new-var (cdr (assq var new-renames)))
                                                             (walked-lam (walk (cadr c) '() new-renames)))
                                                        (set! lifted-defs (cons `(define ,new-var ,walked-lam) lifted-defs))))
                                                    final-liftable)

                                          (let* ((residual-sets (map (lambda (s) `(set! ,(cadr s) ,(walk (caddr s) new-env new-renames)))
                                                                     (filter (lambda (s) (not (hashtable-contains? liftable-ht (cadr s)))) sets)))
                                                 (residual-body (map (lambda (x) (walk x new-env new-renames)) b))
                                                 (residual-bindings (let loop-bind ((bs bindings))
                                                                      (cond ((null? bs) '())
                                                                            ((hashtable-contains? liftable-ht (caar bs)) (loop-bind (cdr bs)))
                                                                            (else (cons (list (caar bs) (walk (cadar bs) env new-renames)) (loop-bind (cdr bs))))))))
                                            (if (and (null? residual-bindings) (null? residual-sets))
                                                (if (= (length residual-body) 1) (car residual-body) `(begin ,@residual-body))
                                                `(let ,residual-bindings ,@residual-sets ,@residual-body)))))))))))))

                (define (process-letrec* e)
                  (let* ((bindings (cadr e))
                         (vars (map car bindings))
                         (body (cddr e))
                         (new-env (append vars env))
                         ;; Identify lambda bindings as lift candidates
                         (candidates (filter (lambda (c) c)
                                      (map (lambda (b)
                                             (let ((var (car b)) (val (cadr b)))
                                               (if (and (pair? val) (eq? (car val) 'lambda))
                                                   (list var val (analyze-free-vars-optimizer val '()))
                                                   #f)))
                                           bindings))))
                    ;; Fixpoint: remove candidates whose free vars reference forbidden (env-external) symbols
                    (let fixpoint ((forbidden-ht (let ((ht (make-eq-hashtable)))
                                                   (for-each (lambda (v) (hashtable-set! ht v #t))
                                                             (append env (remove-from-list vars (map car candidates))))
                                                   ht))
                                   (current-candidates candidates))
                      (let loop-cand ((rest current-candidates) (new-candidates '()) (changed #f))
                        (if (pair? rest)
                            (let* ((c (car rest)) (var (car c)) (lam (cadr c)) (fv (caddr c)))
                              (if (not (any-in-set? fv forbidden-ht))
                                  (loop-cand (cdr rest) (cons c new-candidates) changed)
                                  (begin (hashtable-set! forbidden-ht var #t)
                                         (loop-cand (cdr rest) new-candidates #t))))
                            (if changed
                                (fixpoint forbidden-ht (reverse new-candidates))
                                (let* ((final-liftable (reverse new-candidates))
                                       (liftable-vars (map car final-liftable))
                                       (liftable-ht (make-eq-hashtable))
                                       (_ (for-each (lambda (v) (hashtable-set! liftable-ht v #t)) liftable-vars))
                                       (new-renames (append (map (lambda (var) (cons var (generate-lifted-name var))) liftable-vars) renames)))

                                  ;; Emit lifted definitions
                                  (for-each (lambda (c)
                                              (let* ((var (car c))
                                                     (new-var (cdr (assq var new-renames)))
                                                     (walked-lam (walk (cadr c) '() new-renames)))
                                                (set! lifted-defs (cons `(define ,new-var ,walked-lam) lifted-defs))))
                                            final-liftable)

                                  ;; Build residual bindings (non-lifted) and body
                                  (let* ((residual-bindings (filter (lambda (b) (not (hashtable-contains? liftable-ht (car b))))
                                                                    (map (lambda (b) (list (car b) (walk (cadr b) new-env new-renames))) bindings)))
                                         (residual-body (map (lambda (x) (walk x new-env new-renames)) body)))
                                    (if (null? residual-bindings)
                                        (if (= (length residual-body) 1) (car residual-body) `(begin ,@residual-body))
                                        `(letrec* ,residual-bindings ,@residual-body))))))))))

                (cond ((symbol? e) (lookup e))
                      ((not (pair? e)) e)
                      ((eq? (car e) 'quote) e)
                      ((eq? (car e) 'if)
                       `(if ,(walk (cadr e) env renames)
                            ,(walk (caddr e) env renames)
                            ,(if (null? (cdddr e)) '(unspecified) (walk (cadddr e) env renames))))
                      ((eq? (car e) 'begin)
                       `(begin ,@(map (lambda (x) (walk x env renames)) (cdr e))))
                      ((eq? (car e) 'set!)
                       `(set! ,(lookup (cadr e)) ,(walk (caddr e) env renames)))
                      ((eq? (car e) 'define) (process-define e))
                      ((eq? (car e) 'lambda) (process-lambda e))
                      ((eq? (car e) 'let) (process-let e))
                      ((eq? (car e) 'letrec*) (process-letrec* e))
                      (else (map (lambda (x) (walk x env renames)) e))))))
      (let ((new-expr (walk expr '() '())))
        (if (null? lifted-defs)
            new-expr
            `(begin ,@(reverse lifted-defs) ,new-expr))))))
