
;; --- Utility: Set Operations ---
(define (set-union s1 s2)
  (if (null? s1) s2
      (let ((rest (set-union (cdr s1) s2)))
        (if (memq (car s1) s2) rest (cons (car s1) rest)))))

(define (set-minus s1 s2)
  (if (null? s1) '()
      (let ((rest (set-minus (cdr s1) s2)))
        (if (memq (car s1) s2) rest (cons (car s1) rest)))))

;; --- Analysis 1: Free Variables ---
(define (analyze-free-vars expr bound-vars)
  (cond
    ((symbol? expr) (if (memq expr bound-vars) '() (list expr)))
    ((not (pair? expr)) '())
    ((eq? (car expr) 'quote) '())
    ((eq? (car expr) 'if)
     (set-union (analyze-free-vars (cadr expr) bound-vars)
                (set-union (analyze-free-vars (caddr expr) bound-vars)
                           (if (null? (cdddr expr)) '() (analyze-free-vars (cadddr expr) bound-vars)))))
    ((eq? (car expr) 'begin)
     (let loop ((exprs (cdr expr)))
       (if (null? exprs) '() (set-union (analyze-free-vars (car exprs) bound-vars) (loop (cdr exprs))))))
    ((eq? (car expr) 'set!)
     (let ((var (cadr expr)) (val (caddr expr)))
       (set-union (if (memq var bound-vars) '() (list var)) (analyze-free-vars val bound-vars))))
    ((eq? (car expr) 'define) (analyze-free-vars (caddr expr) (cons (cadr expr) bound-vars)))
    ((eq? (car expr) 'lambda)
     (let ((params (cadr expr)) (body (cddr expr)))
       (let ((new-bound (if (list? params) params (list params))))
         (let ((body-free (let loop ((exprs body))
                            (if (null? exprs) '() (set-union (analyze-free-vars (car exprs) (append new-bound bound-vars)) (loop (cdr exprs)))))))
           (set-minus body-free (append new-bound bound-vars))))))
    ((eq? (car expr) 'let)
     (let ((bindings (cadr expr)) (body (cddr expr)))
       (let ((vars (map car bindings)) (vals (map cadr bindings)))
         (set-union (let loop ((vs vals)) (if (null? vs) '() (set-union (analyze-free-vars (car vs) bound-vars) (loop (cdr vs)))))
                    (let ((body-free (let loop ((exprs body))
                                       (if (null? exprs) '() (set-union (analyze-free-vars (car exprs) (append vars bound-vars)) (loop (cdr exprs)))))))
                      (set-minus body-free (append vars bound-vars)))))))
    (else (let loop ((exprs expr)) (if (null? exprs) '() (set-union (analyze-free-vars (car exprs) bound-vars) (loop (cdr exprs))))))))

;; --- Analysis 2: Mutated Variables ---
(define (analyze-mutated-vars expr)
  (cond
    ((pair? expr)
     (case (car expr)
       ((quote) '())
       ((set!) (cons (cadr expr) (analyze-mutated-vars (caddr expr))))
       ((lambda) (let loop ((body (cddr expr))) (if (null? body) '() (set-union (analyze-mutated-vars (car body)) (loop (cdr body))))))
       (else (let loop ((exprs expr)) (if (null? exprs) '() (set-union (analyze-mutated-vars (car exprs)) (loop (cdr exprs))))))))
    (else '())))

(define (compile expr)
  (let* ((mutated (analyze-mutated-vars expr))
         (labels 0)
         (closure-labels 0)
         (compiled-code '())
         (all-closure-code '()))

    (define (gen-label . type)
      (if (and (not (null? type)) (eq? (car type) 'closure))
          (begin (set! closure-labels (+ closure-labels 1)) (string->symbol (string-append "C" (number->string closure-labels))))
          (begin (set! labels (+ labels 1)) (string->symbol (string-append "L" (number->string labels))))))

    (define (emit inst) (set! compiled-code (cons inst compiled-code)))
    (define (make-reg i) (string->symbol (string-append "r" (number->string i))))

    (define (lookup var env)
      (let loop ((e env))
        (if (null? e) (cons 'global var)
            (let ((scope (car e)))
              (if (and (pair? scope) (eq? (car scope) 'cl))
                  (let ((res (assoc var (cdr scope))))
                    (if res (cons 'cl (cdr res)) (loop (cdr e))))
                  (let ((res (assoc var scope)))
                    (if res (cons 'reg (cdr res)) (loop (cdr e)))))))))

    (define (codegen-symbol expr env tail?)
      (let ((binding (lookup expr env)))
        (cond
          ((eq? (car binding) 'reg) (if (memq expr mutated) (emit `(reg-cell-ref r0 ,(cdr binding))) (emit `(mov r0 ,(cdr binding)))))
          ((eq? (car binding) 'cl) (if (memq expr mutated) (emit `(closure-cell-ref r0 ,(cdr binding))) (emit `(closure-ref r0 ,(cdr binding)))))
          (else (emit `(global-ref r0 ,expr))))
        (if tail? (emit `(ret)))))

    (define (codegen-if expr env next-reg tail?)
      (let ((t-label (gen-label)) (f-label (gen-label)) (end-label (gen-label)))
        (codegen (cadr expr) env next-reg #f)
        (emit `(if ,t-label ,f-label))
        (emit `(label ,t-label))
        (codegen (caddr expr) env next-reg tail?)
        (if (not tail?) (emit `(jump ,end-label)))
        (emit `(label ,f-label))
        (if (null? (cdddr expr))
            (begin (emit `(const r0 #f)) (if tail? (emit `(ret))))
            (codegen (cadddr expr) env next-reg tail?))
        (if (not tail?) (emit `(label ,end-label)))))

    (define (codegen-set! expr env next-reg tail?)
      (let ((var (cadr expr)) (val (caddr expr)))
        (codegen val env next-reg #f)
        (let ((binding (lookup var env)))
          (cond
            ((eq? (car binding) 'reg) (if (memq var mutated) (emit `(reg-cell-set! ,(cdr binding) r0)) (emit `(mov ,(cdr binding) r0))))
            ((eq? (car binding) 'cl) (emit `(closure-cell-set! ,(cdr binding) r0)))
            (else (emit `(global-set! ,var r0))))
          (if tail? (emit `(ret))))))

    (define (codegen-lambda expr env next-reg tail?)
      (let* ((params (cadr expr)) (body (cddr expr))
             (all-free (analyze-free-vars expr '()))
             (params-list (if (list? params) params (list params)))
             (potential-free (set-minus all-free params-list))
             (free (filter (lambda (f) (let ((b (lookup f env))) (not (eq? (car b) 'global)))) potential-free))
             (n-params (length params-list))
             (entry-label (gen-label 'closure))
             (prev-compiled-code compiled-code))
        (set! compiled-code '())
        (emit `(label ,entry-label))
        (let* ((new-base (+ n-params 1))
               (new-scope (let loop ((p params) (i 0))
                            (if (null? p) '() (cons (cons (car p) (make-reg (+ new-base i))) (loop (cdr p) (+ i 1))))))
               (cl-scope (let loop ((f free) (i 0))
                           (if (null? f) '() (cons (cons (car f) i) (loop (cdr f) (+ i 1)))))))
          (let move-params ((i 0))
            (if (< i n-params) (begin (emit `(mov ,(make-reg (+ new-base i)) ,(make-reg i))) (move-params (+ i 1)))))
          (for-each (lambda (p) (if (memq (car p) mutated) (emit `(make-cell ,(cdr p) ,(cdr p))))) new-scope)
          (codegen `(begin ,@body) (cons (cons `num-params n-params) (cons new-scope (list (cons 'cl cl-scope)))) (+ new-base n-params) #t))
        (set! all-closure-code (cons (reverse compiled-code) all-closure-code))
        (set! compiled-code prev-compiled-code)
        (let ((free-regs (map (lambda (f) (let ((b (lookup f env))) (cdr b))) free)))
          (emit `(make-closure r0 ,entry-label ,free-regs)) (if tail? (emit `(ret))))))

    (define (codegen-let expr env next-reg tail?)
      (let* ((bindings (cadr expr)) (body (cddr expr)) (vars (map car bindings)) (vals (map cadr bindings)))
        (let loop ((vs vals) (vars vars) (r next-reg) (new-scope '()))
          (if (null? vs) (codegen `(begin ,@body) (cons new-scope env) r tail?)
              (let ((reg (make-reg r)))
                (codegen (car vs) env (+ r 1) #f) (emit `(mov ,reg r0))
                (if (memq (car vars) mutated) (emit `(make-cell ,reg ,reg)))
                (loop (cdr vs) (cdr vars) (+ r 1) (cons (cons (car vars) reg) new-scope)))))))

    (define (codegen-application expr env next-reg tail?)
      (let* ((proc (car expr)) (args (cdr expr))
             (num-args (length args))
             (base-reg (max 1 next-reg)))
        (let loop ((as args) (i 0))
          (if (null? as)
              (let ((call-reg (make-reg (+ base-reg num-args))))
                (codegen proc env (+ base-reg num-args 1) #f)
                (emit `(mov ,call-reg r0))
                (let move-loop ((j 0))
                  (if (< j num-args)
                      (begin (emit `(mov ,(make-reg j) ,(make-reg (+ base-reg j)))) (move-loop (+ j 1)))))
                (if tail? (emit `(tail-call ,call-reg ,num-args)) (emit `(call ,call-reg ,num-args))))
              (let ((temp-reg (make-reg (+ base-reg i))))
                (codegen (car as) env (+ base-reg num-args 1) #f)
                (emit `(mov ,temp-reg r0))
                (loop (cdr as) (+ i 1)))))))

    (define (codegen expr env next-reg tail?)
      (cond
        ((symbol? expr) (codegen-symbol expr env tail?))
        ((not (pair? expr)) (emit `(const r0 ,expr)) (if tail? (emit `(ret))))
        ((eq? (car expr) 'quote) (emit `(const r0 ,(cadr expr))) (if tail? (emit `(ret))))
        ((eq? (car expr) 'begin)
         (let loop ((exprs (cdr expr)))
           (if (null? (cdr exprs)) (codegen (car exprs) env next-reg tail?)
               (begin (codegen (car exprs) env next-reg #f) (loop (cdr exprs))))))
        ((eq? (car expr) 'define)
         (let ((var (cadr expr)) (val (caddr expr)))
           (codegen val env next-reg #f) (emit `(global-set! ,var r0)) (emit `(global-ref r0 ,var)) (if tail? (emit `(ret)))))
        ((eq? (car expr) 'if) (codegen-if expr env next-reg tail?))
        ((eq? (car expr) 'set!) (codegen-set! expr env next-reg tail?))
        ((eq? (car expr) 'lambda) (codegen-lambda expr env next-reg tail?))
        ((eq? (car expr) 'let) (codegen-let expr env next-reg tail?))
        (else (codegen-application expr env next-reg tail?))))

    (codegen expr '() 1 #f)
    (emit `(ret))

    (let* ((main-code (reverse compiled-code))
           (closure-code (apply append (reverse all-closure-code)))
           (all-code (append main-code closure-code))
           (label-map (make-hash-table 'eq?))
           (final-code '()) (current-pc 0))
      (for-each (lambda (inst)
                  (if (eq? (car inst) 'label)
                      (hash-table-put! label-map (cadr inst) current-pc)
                      (set! current-pc (+ current-pc 1))))
                all-code)
      (for-each (lambda (inst)
                  (if (not (eq? (car inst) 'label))
                      (let ((resolved (map (lambda (x)
                                             (if (and (symbol? x) (hash-table-exists? label-map x))
                                                 (hash-table-get label-map x) x))
                                           inst)))
                        (set! final-code (cons (list->vector resolved) final-code)))))
                all-code)
      (list->vector (reverse final-code)))))
