
;; --- Instruction Sets ---
(define cp:ops-loads '(const mov global-ref closure-ref closure-cell-ref reg-cell-ref))
(define cp:ops-overwrites '(const mov global-ref closure-ref closure-cell-ref reg-cell-ref)) ; ops that overwrite a register

;; --- Utility: Set Operations ---
(define (cp:set-union s1 s2)
  (if (null? s1) s2
      (let ((rest (cp:set-union (cdr s1) s2)))
        (if (memq (car s1) s2) rest (cons (car s1) rest)))))

(define (cp:set-minus s1 s2)
  (if (null? s1) '()
      (let ((rest (cp:set-minus (cdr s1) s2)))
        (if (memq (car s1) s2) rest (cons (car s1) rest)))))

;; --- Analysis 1: Free Variables ---
(define (cp:analyze-free-vars expr bound-vars)
  (cond
    ((symbol? expr) (if (memq expr bound-vars) '() (list expr)))
    ((not (pair? expr)) '())
    ((eq? (car expr) 'quote) '())
    ((eq? (car expr) 'if)
     (cp:set-union (cp:analyze-free-vars (cadr expr) bound-vars)
                (cp:set-union (cp:analyze-free-vars (caddr expr) bound-vars)
                           (if (null? (cdddr expr)) '() (cp:analyze-free-vars (cadddr expr) bound-vars)))))
    ((eq? (car expr) 'begin)
     (let loop ((exprs (cdr expr)))
       (if (null? exprs) '() (cp:set-union (cp:analyze-free-vars (car exprs) bound-vars) (loop (cdr exprs))))))
    ((eq? (car expr) 'set!)
     (let ((var (cadr expr)) (val (caddr expr)))
       (cp:set-union (if (memq var bound-vars) '() (list var)) (cp:analyze-free-vars val bound-vars))))
    ((eq? (car expr) 'define)
     (let ((head (cadr expr)))
       (if (pair? head)
           (cp:analyze-free-vars `(lambda ,(cdr head) ,@(cddr expr)) (cons (car head) bound-vars))
           (cp:analyze-free-vars (caddr expr) (cons head bound-vars)))))
    ((eq? (car expr) 'lambda)
     (let ((params (cadr expr)) (body (cddr expr)))
       (let ((new-bound (if (list? params) params (list params))))
         (let ((body-free (let loop ((exprs body))
                            (if (null? exprs) '() (cp:set-union (cp:analyze-free-vars (car exprs) (append new-bound bound-vars)) (loop (cdr exprs)))))))
           (cp:set-minus body-free (append new-bound bound-vars))))))
    ((eq? (car expr) 'let)
     (let ((bindings (cadr expr)) (body (cddr expr)))
       (let ((vars (map car bindings)) (vals (map cadr bindings)))
         (cp:set-union (let loop ((vs vals)) (if (null? vs) '() (cp:set-union (cp:analyze-free-vars (car vs) bound-vars) (loop (cdr vs)))))
                    (let ((body-free (let loop ((exprs body))
                                       (if (null? exprs) '() (cp:set-union (cp:analyze-free-vars (car exprs) (append vars bound-vars)) (loop (cdr exprs)))))))
                      (cp:set-minus body-free (append vars bound-vars)))))))
    (else (let loop ((exprs expr)) (if (null? exprs) '() (cp:set-union (cp:analyze-free-vars (car exprs) bound-vars) (loop (cdr exprs))))))))

;; --- Check Recursive Pattern ---
(define (cp:match-rec-pattern expr)
  (and (pair? expr)
       (eq? (car expr) 'let)
       (let ((bindings (cadr expr))
             (body (cddr expr)))
         (and (pair? bindings)
              (null? (cdr bindings))
              (let ((name (car (car bindings))))
                (and (symbol? name)
                     (pair? body)
                     (pair? (car body))
                     (eq? (car (car body)) 'set!)
                     (eq? (cadr (car body)) name)
                     (pair? (caddr (car body)))
                     (eq? (car (caddr (car body))) 'lambda)))))))

;; --- Analysis 2: Mutated Variables ---
(define (cp:analyze-mutated-vars expr rec-vars)
  (cond
    ((pair? expr)
     (case (car expr)
       ((quote) '())
       ((set!) (if (memq (cadr expr) rec-vars)
                   (cp:analyze-mutated-vars (caddr expr) rec-vars)
                   (cons (cadr expr) (cp:analyze-mutated-vars (caddr expr) rec-vars))))
       ((lambda) (let loop ((body (cddr expr))) (if (null? body) '() (cp:set-union (cp:analyze-mutated-vars (car body) rec-vars) (loop (cdr body))))))
       (else (let loop ((exprs expr)) (if (null? exprs) '() (cp:set-union (cp:analyze-mutated-vars (car exprs) rec-vars) (loop (cdr exprs))))))))
    (else '())))


;; --- Optimization: Peephole ---
(define (cp:optimize-swap code)
  ;; Pattern: (mov A B) (mov B A) -> (mov A B)
  (if (and (null? (cddr code)) ; exactly two if we are at the end, but usually we look ahead
           (pair? (car code)) (eq? (caar code) 'mov)
           (pair? (cadr code)) (eq? (caadr code) 'mov)
           (eq? (cadr (car code)) (caddr (cadr code)))
           (eq? (caddr (car code)) (cadr (cadr code))))
      (list (car code))
      #f))

(define (cp:optimize-three-inst code)
  (if (null? (cddr code)) #f
      (let ((i1 (car code)) (i2 (cadr code)) (i3 (caddr code)))
        (if (and (pair? i1) (memq (car i1) cp:ops-loads)
                 (pair? i2) (memq (car i2) cp:ops-loads)
                 (pair? i3) (memq (car i3) cp:ops-loads))
            (let ((dst1 (cadr i1)) (src1 (caddr i1))
                  (dst2 (cadr i2)) (src2 (caddr i2))
                  (dst3 (cadr i3)) (src3 (caddr i3)))
              (cond
               ;; Pattern 1: Load/Mov A->C, Mov D->A (overwriting A)
               ((and (memq (car i1) (delete 'mov cp:ops-loads))
                     (eq? dst1 src2)
                     (eq? dst1 dst3))
                (cons `(,(car i1) ,dst2 ,src1) (cons i3 (cdddr code))))
               
               ;; Pattern 2: Mov A->B, Mov C->A (overwriting A), Mov A->D ??
               ((and (eq? (car i1) 'mov)
                     (eq? dst1 src2)
                     (eq? dst1 dst3)
                     (not (eq? dst1 src3)))
                (cons `(mov ,dst2 ,src1) (cons i3 (cdddr code))))

               ;; Pattern 3: Redundant Restore
               ;; (mov rA rB) (op rC <data>) (mov rB rA) -> (mov rA rB) (op rC <data>)
               ;; Condition: rC != rA && rC != rB
               ((and (eq? (car i1) 'mov)
                     (memq (car i2) (delete 'mov cp:ops-loads))
                     (eq? (car i3) 'mov)
                     (eq? dst1 src3)       ; rA == rA in (mov rB rA)
                     (eq? src1 dst3)       ; rB == rB in (mov rB rA)
                     (not (eq? dst2 dst1)) ; rC != rA
                     (not (eq? dst2 src1))); rC != rB
                (cons i1 (cons i2 (cdddr code))))
               
               (else #f)))
            #f))))

(define (cp:peephole-optimize-pass code)
  (cond
    ((null? code) '())
    ((null? (cdr code)) code)
    ;; Try 2-inst optimizations
    ((and (pair? (car code)) (eq? (caar code) 'mov)
          (pair? (cadr code)) (eq? (caadr code) 'mov)
          (eq? (cadr (car code)) (caddr (cadr code)))
          (eq? (caddr (car code)) (cadr (cadr code))))
     (cp:peephole-optimize-pass (cons (car code) (cddr code))))
    
    ;; Try 3-inst optimizations
    ((cp:optimize-three-inst code) => cp:peephole-optimize-pass)

    (else (cons (car code) (cp:peephole-optimize-pass (cdr code))))))


(define (cp:peephole-optimize code)
  (let loop ((current code))
    (let ((next (cp:peephole-optimize-pass current)))
      (if (equal? current next)
          current
          (loop next)))))

;; --- Optimization: Analyze Max Outgoing Args ---
(define (cp:analyze-max-outgoing-args expr)
  (cond
   ((not (pair? expr)) 0)
   ((symbol? (car expr))
    (case (car expr)
      ((quote) 0)
      ((if) (max (cp:analyze-max-outgoing-args (cadr expr))
                 (cp:analyze-max-outgoing-args (caddr expr))
                 (if (null? (cdddr expr)) 0 (cp:analyze-max-outgoing-args (cadddr expr)))))
      ((begin) (apply max 0 (map cp:analyze-max-outgoing-args (cdr expr))))
      ((set!) (cp:analyze-max-outgoing-args (caddr expr)))
      ((lambda) 0) ;; New scope
      ((let)
       (let ((bindings (cadr expr)) (body (cddr expr)))
         (max (apply max 0 (map (lambda (b) (cp:analyze-max-outgoing-args (cadr b))) bindings))
              (apply max 0 (map cp:analyze-max-outgoing-args body)))))
      (else ;; Application
       (let ((args (cdr expr))
             (proc (car expr)))
         (max (length args)
              (cp:analyze-max-outgoing-args proc)
              (apply max 0 (map cp:analyze-max-outgoing-args args)))))))
   (else ;; Should not happen in this simplified scheme, but recurse just in case
    (apply max 0 (map cp:analyze-max-outgoing-args expr)))))

(define (cp:compile expr)
  (let* ((rec-vars '())
         (_ (let walk ((e expr))
              (if (cp:match-rec-pattern e) (set! rec-vars (cons (car (car (cadr e))) rec-vars)))
              (if (pair? e) (if (eq? (car e) 'quote) '() (for-each walk e)))))


         (mutated (cp:analyze-mutated-vars expr rec-vars))
         (labels 0)
         (closure-labels 0)
         (compiled-code '())
         (all-closure-code '()))

    (define (gen-label . type)
      (if (and (not (null? type)) (eq? (car type) 'closure))
          (begin (set! closure-labels (+ closure-labels 1)) (string->symbol (string-append "C" (number->string closure-labels))))
          (begin (set! labels (+ labels 1)) (string->symbol (string-append "L" (number->string labels))))))

    (define (emit inst) (set! compiled-code (cons inst compiled-code)))
    (define (make-reg i) (string->symbol (string-append "r" (number->string i))))

    (define (codegen-args args env arg-base)
      (let loop ((as args) (i 0))
        (if (not (null? as))
            (let ((temp-reg (make-reg (+ arg-base i))))
              (codegen (car as) env (+ arg-base i 1) #f)
              (emit `(mov ,temp-reg r0))
              (loop (cdr as) (+ i 1))))))

    (define (move-args num-args base)
      (let move-loop ((j 0))
        (if (< j num-args)
            (begin (emit `(mov ,(make-reg j) ,(make-reg (+ base j)))) (move-loop (+ j 1))))))

    (define (lookup var env)
      (let loop ((e env))
        (if (null? e) (cons 'global var)
            (let ((scope (car e)))
              (if (and (pair? scope) (eq? (car scope) 'cl))
                  (let ((res (assoc var (cdr scope))))
                    (if res (cons 'cl (cdr res)) (loop (cdr e))))
                  (let ((res (assoc var scope)))
                    (if res 
                        (if (eq? (cdr res) 'self)
                            (cons 'self #f)
                            (cons 'reg (cdr res)))
                        (loop (cdr e)))))))))


    (define (codegen-symbol expr env tail?)
      (let ((binding (lookup expr env)))
        (cond
          ((eq? (car binding) 'reg) (if (memq expr mutated) (emit `(reg-cell-ref r0 ,(cdr binding))) (emit `(mov r0 ,(cdr binding)))))
          ((eq? (car binding) 'cl) (if (memq expr mutated) (emit `(closure-cell-ref r0 ,(cdr binding))) (emit `(closure-ref r0 ,(cdr binding)))))
          ((eq? (car binding) 'self) (emit `(closure-self r0)))
          (else (emit `(global-ref r0 ,expr))))
        (if tail? (emit `(ret)))))


    (define (codegen-if expr env next-reg tail?)
      (let ((t-label (gen-label)) (f-label (gen-label)) (end-label (gen-label)))
        (codegen (cadr expr) env next-reg #f)
        (emit `(if ,t-label ,f-label))
        (emit `(label ,t-label))
        (codegen (caddr expr) env next-reg tail?)
        (if (not tail?) (emit `(jump ,end-label)))
        (emit `(label ,f-label))
        (if (null? (cdddr expr))
            (begin (emit `(const r0 #f)) (if tail? (emit `(ret))))
            (codegen (cadddr expr) env next-reg tail?))
        (if (not tail?) (emit `(label ,end-label)))))

    (define (codegen-set! expr env next-reg tail?)
      (let ((var (cadr expr)) (val (caddr expr)))
        (codegen val env next-reg #f)
        (let ((binding (lookup var env)))
          (cond
            ((eq? (car binding) 'reg) (if (memq var mutated) (emit `(reg-cell-set! ,(cdr binding) r0)) (emit `(mov ,(cdr binding) r0))))
            ((eq? (car binding) 'cl) (emit `(closure-cell-set! ,(cdr binding) r0)))
            (else (emit `(global-set! ,var r0))))
          (if tail? (emit `(ret))))))

    (define (codegen-lambda expr env next-reg tail?)
      (let* ((params (cadr expr)) (body (cddr expr))
             (all-free (cp:analyze-free-vars expr '()))
             (params-list (if (list? params) params (list params)))
             (potential-free (cp:set-minus all-free params-list))
             (free (filter (lambda (f) (let ((b (lookup f env))) (not (or (eq? (car b) 'global) (eq? (car b) 'self))))) potential-free))
             (n-params (length params-list))
             (entry-label (gen-label 'closure))
             (prev-compiled-code compiled-code)
             (max-outgoing (apply max 0 (map cp:analyze-max-outgoing-args body))))
        (set! compiled-code '())
        (emit `(label ,entry-label))
        (let* ((new-base (max 1 max-outgoing)) ; Ensure space for outgoing args
               (new-scope (let loop ((p params) (i 0))
                            (if (null? p) '() (cons (cons (car p) (make-reg (+ new-base i))) (loop (cdr p) (+ i 1))))))
               (cl-scope (let loop ((f free) (i 0))
                           (if (null? f) '() (cons (cons (car f) i) (loop (cdr f) (+ i 1)))))))
          ;; Move params in reverse order to tolerate overlap
          (let move-params ((i (- n-params 1)))
            (if (>= i 0) (begin (emit `(mov ,(make-reg (+ new-base i)) ,(make-reg i))) (move-params (- i 1)))))
          (let* ((self-bindings (let loop ((e env))
                                  (if (null? e) '()
                                      (let ((scope (car e)))
                                        (if (and (pair? scope) (not (eq? (car scope) 'cl)) (not (eq? (car scope) 'num-params)))
                                            (append (filter (lambda (b) (eq? (cdr b) 'self)) scope) (loop (cdr e)))
                                            (loop (cdr e))))))))
            (for-each (lambda (p) (if (memq (car p) mutated) (emit `(make-cell ,(cdr p) ,(cdr p))))) new-scope)
            (codegen `(begin ,@body) (cons (cons `num-params n-params) (cons new-scope (cons self-bindings (list (cons 'cl cl-scope))))) (+ new-base n-params) #t)))
        (set! all-closure-code (cons (reverse compiled-code) all-closure-code))
        (set! compiled-code prev-compiled-code)
        (let ((free-regs (map (lambda (f) (let ((b (lookup f env))) (cdr b))) free)))
          (emit `(make-closure r0 ,entry-label ,free-regs)) (if tail? (emit `(ret))))))

    (define (codegen-application expr env next-reg tail?)
      (if (and (pair? (car expr)) (cp:match-rec-pattern (car expr)))
          (let* ((let-expr (car expr)) (args (cdr expr)) (num-args (length args))
                 (bindings (cadr let-expr)) (name (caar bindings)) (sym (cadar bindings))
                 (body (cddr let-expr)) (set-expr (car body)) (lambda-expr (caddr set-expr))
                 (reg (make-reg next-reg)) (arg-base (+ next-reg 1)))
            (emit `(const r0 ,sym)) (emit `(mov ,reg r0))
            (codegen-lambda lambda-expr (cons (list (cons name 'self)) env) next-reg #f)
            (emit `(mov ,reg r0))
            (codegen-args args (cons (list (cons name reg)) env) arg-base)
            (let ((call-reg (make-reg (+ arg-base num-args))))
              (emit `(mov ,call-reg ,reg))
              (move-args num-args arg-base)
              (if tail? (emit `(tail-call ,call-reg ,num-args)) (emit `(call ,call-reg ,num-args)))))

          (let* ((proc (car expr)) (args (cdr expr)) (num-args (length args))
                 (base-reg (max 1 next-reg)))
            (codegen-args args env base-reg)
            (let ((call-reg (make-reg (+ base-reg num-args))))
              (codegen proc env (+ base-reg num-args) #f)
              (emit `(mov ,call-reg r0))
              (move-args num-args base-reg)
              (if tail? (emit `(tail-call ,call-reg ,num-args)) (emit `(call ,call-reg ,num-args)))))))

    (define (codegen-let expr env next-reg tail?)
      (if (cp:match-rec-pattern expr)
          (let* ((bindings (cadr expr))
                 (name (caar bindings))
                 (sym (cadar bindings))
                 (body (cddr expr))
                 (reg (make-reg next-reg)))
            (emit `(const r0 ,sym))
            (emit `(mov ,reg r0))
            (let ((set-expr (car body))
                  (rest (cdr body)))
              (let ((lambda-expr (caddr set-expr)))
                (codegen-lambda lambda-expr (cons (list (cons name 'self)) env) (+ next-reg 1) #f))
              (emit `(mov ,reg r0))
              (codegen `(begin ,@rest) (cons (list (cons name reg)) env) (+ next-reg 1) tail?)))
          (let* ((bindings (cadr expr)) (body (cddr expr)) (vars (map car bindings)) (vals (map cadr bindings)))
            (let loop ((vs vals) (vars vars) (r next-reg) (new-scope '()))
              (if (null? vs) (codegen `(begin ,@body) (cons new-scope env) r tail?)
                  (let ((reg (make-reg r)))
                    (codegen (car vs) env (+ r 1) #f) (emit `(mov ,reg r0))
                    (if (memq (car vars) mutated) (emit `(make-cell ,reg ,reg)))
                    (loop (cdr vs) (cdr vars) (+ r 1) (cons (cons (car vars) reg) new-scope))))))))



    (define (codegen expr env next-reg tail?)
      (cond
        ((symbol? expr) (codegen-symbol expr env tail?))
        ((not (pair? expr)) (emit `(const r0 ,expr)) (if tail? (emit `(ret))))
        ((eq? (car expr) 'quote) (emit `(const r0 ,(cadr expr))) (if tail? (emit `(ret))))
        ((eq? (car expr) 'begin)
         (let loop ((exprs (cdr expr)))
           (if (null? (cdr exprs)) (codegen (car exprs) env next-reg tail?)
               (begin (codegen (car exprs) env next-reg #f) (loop (cdr exprs))))))
        ((eq? (car expr) 'define)
         (let ((var (cadr expr)) (val (caddr expr)))
           (codegen val env next-reg #f) (emit `(global-set! ,var r0)) (emit `(global-ref r0 ,var)) (if tail? (emit `(ret)))))
        ((eq? (car expr) 'if) (codegen-if expr env next-reg tail?))
        ((eq? (car expr) 'set!) (codegen-set! expr env next-reg tail?))
        ((eq? (car expr) 'lambda) (codegen-lambda expr env next-reg tail?))
        ((eq? (car expr) 'let) (codegen-let expr env next-reg tail?))
        (else (codegen-application expr env next-reg tail?))))

    (codegen expr '() (max 1 (cp:analyze-max-outgoing-args expr)) #f)
    (emit `(ret))

    (let* ((main-code (reverse compiled-code))
           (closure-code (apply append (reverse all-closure-code)))
           (all-code (cp:peephole-optimize (append main-code closure-code)))
           (label-map (make-hash-table 'eq?))
           (final-code '()) (current-pc 0))
      ;(newline)
      ;(display all-code)
      ;(newline)
      (for-each (lambda (inst)
                  (if (eq? (car inst) 'label)
                      (hash-table-put! label-map (cadr inst) current-pc)
                      (set! current-pc (+ current-pc 1))))
                all-code)
      (for-each (lambda (inst)
                  (if (not (eq? (car inst) 'label))
                      (let ((resolved (map (lambda (x)
                                             (if (and (symbol? x) (hash-table-exists? label-map x))
                                                 (hash-table-get label-map x) x))
                                           inst)))
                        (set! final-code (cons (list->vector resolved) final-code)))))
                all-code)
      (list->vector (reverse final-code)))))
