
;; Register-based VM for Scheme
(use srfi-9)
(use srfi-1)

(define-record-type <vm>
  (make-vm-internal globals)
  vm?
  (globals vm-globals vm-globals-set!))

(define-record-type <context>
  (make-context code pc stack cl regs vm)
  context?
  (code    ctx-code    ctx-code-set!)
  (pc      ctx-pc      ctx-pc-set!)
  (stack   ctx-stack   ctx-stack-set!)
  (cl      ctx-cl      ctx-cl-set!)
  (regs    ctx-regs    ctx-regs-set!)
  (vm      ctx-vm      ctx-vm-set!))

(define (vm:decode-reg reg)
  (if (symbol? reg)
      (let ((s (symbol->string reg)))
        (if (and (> (string-length s) 1) (char=? (string-ref s 0) #\r))
            (string->number (substring s 1 (string-length s)))
            (error "Invalid register name" reg)))
      reg))

(define (vm:reg-ref ctx reg)
  (vector-ref (ctx-regs ctx) (vm:decode-reg reg)))

(define (vm:reg-set! ctx reg val)
  (vector-set! (ctx-regs ctx) (vm:decode-reg reg) val))

(define-record-type <closure>
  (make-closure-vec label free)
  closure?
  (label closure-label)
  (free  closure-free))

(define-record-type <cell>
  (make-cell-box value)
  cell?
  (value cell-value cell-value-set!))

(define (vm:init-vm)
  (make-vm-internal (make-hash-table 'eq?)))

(define (vm:init-context vm code)
  (make-context code 0 '() #f (make-vector 64 #f) vm))

(define (vm:vm-run ctx)
  (let loop ()
    (let* ((code (ctx-code ctx))
           (pc (ctx-pc ctx)))
      (if (>= pc (vector-length code))
          (vm:reg-ref ctx 'r0)
          (let ((inst (vector-ref code pc)))
            (ctx-pc-set! ctx (+ pc 1))
            (case (vector-ref inst 0)
              ((nop) (loop))
              ((const)
               (let ((reg (vector-ref inst 1)) (val (vector-ref inst 2)))
                 (vm:reg-set! ctx reg val) (loop)))
              ((mov)
               (let ((dst (vector-ref inst 1)) (src (vector-ref inst 2)))
                 (vm:reg-set! ctx dst (vm:reg-ref ctx src)) (loop)))
              ((if)
               (let ((t-label (vector-ref inst 1)) (f-label (vector-ref inst 2)))
                 (if (vm:reg-ref ctx 'r0) (ctx-pc-set! ctx t-label) (ctx-pc-set! ctx f-label)) (loop)))
              ((global-ref)
               (let ((reg (vector-ref inst 1)) (var (vector-ref inst 2)))
                 (vm:reg-set! ctx reg (hash-table-get (vm-globals (ctx-vm ctx)) var)) (loop)))
              ((global-set!)
               (let ((var (vector-ref inst 1)) (src (vector-ref inst 2)))
                 (hash-table-put! (vm-globals (ctx-vm ctx)) var (vm:reg-ref ctx src)) (loop)))
              ((jump)
               (let ((label (vector-ref inst 1)))
                 (ctx-pc-set! ctx label) (loop)))
              ((call)
               (let ((proc-reg (vector-ref inst 1)) (n-args (vector-ref inst 2)))
                 (let ((proc (vm:reg-ref ctx proc-reg)))
                   (if (closure? proc)
                       (begin
                         (ctx-stack-set! ctx (cons (list (ctx-pc ctx) (ctx-cl ctx) (vector-copy (ctx-regs ctx))) (ctx-stack ctx)))
                         (ctx-cl-set! ctx proc) (ctx-pc-set! ctx (closure-label proc)) (loop))
                       (let ((args (let arg-loop ((i 0))
                                     (if (= i n-args) '()
                                         (cons (vm:reg-ref ctx (string->symbol (string-append "r" (number->string i))))
                                               (arg-loop (+ i 1))))))
                             (saved-regs (vector-copy (ctx-regs ctx))))
                         (let ((res (apply proc args)))
                           (ctx-regs-set! ctx saved-regs)
                           (vm:reg-set! ctx 'r0 res) (loop)))))))
              ((tail-call)
               (let ((proc-reg (vector-ref inst 1)) (n-args (vector-ref inst 2)))
                 (let ((proc (vm:reg-ref ctx proc-reg)))
                   (if (closure? proc)
                       (begin (ctx-cl-set! ctx proc) (ctx-pc-set! ctx (closure-label proc)) (loop))
                       (let ((args (let arg-loop ((i 0))
                                       (if (= i n-args) '()
                                           (cons (vm:reg-ref ctx (string->symbol (string-append "r" (number->string i))))
                                                 (arg-loop (+ i 1)))))))
                         (let ((res (apply proc args)))
                           (if (null? (ctx-stack ctx)) res
                               (let ((ctx-data (car (ctx-stack ctx))))
                                 (ctx-pc-set! ctx (car ctx-data)) (ctx-cl-set! ctx (cadr ctx-data)) (ctx-regs-set! ctx (caddr ctx-data))
                                 (ctx-stack-set! ctx (cdr (ctx-stack ctx)))
                                 (vm:reg-set! ctx 'r0 res) (loop)))))))))
              ((ret)
               (if (null? (ctx-stack ctx)) (vm:reg-ref ctx 'r0)
                   (let ((ctx-data (car (ctx-stack ctx)))
                         (res (vm:reg-ref ctx 'r0)))
                     (ctx-pc-set! ctx (car ctx-data)) (ctx-cl-set! ctx (cadr ctx-data)) (ctx-regs-set! ctx (caddr ctx-data))
                     (ctx-stack-set! ctx (cdr (ctx-stack ctx)))
                     (vm:reg-set! ctx 'r0 res) (loop))))

              ((make-closure)
               (let ((dst (vector-ref inst 1)) (label (vector-ref inst 2)) (free-indices (vector-ref inst 3)))
                 (let ((free-vals (map (lambda (idx) (vm:reg-ref ctx idx)) free-indices)))
                   (let ((cl (make-closure-vec label (list->vector free-vals))))
                     (vm:reg-set! ctx dst cl)) (loop))))
              ((closure-ref)
               (let ((reg (vector-ref inst 1)) (idx (vector-ref inst 2)))
                 (vm:reg-set! ctx reg (vector-ref (closure-free (ctx-cl ctx)) idx)) (loop)))
              ((closure-cell-ref)
               (let ((reg (vector-ref inst 1)) (idx (vector-ref inst 2)))
                 (let ((val (vector-ref (closure-free (ctx-cl ctx)) idx)))
                   (let ((extracted (if (cell? val) (cell-value val) val)))
                     (vm:reg-set! ctx reg extracted)) (loop))))
              ((closure-set!)
               (let ((idx (vector-ref inst 1)) (src (vector-ref inst 2)))
                 (vector-set! (closure-free (ctx-cl ctx)) idx (vm:reg-ref ctx src)) (loop)))
              ((closure-cell-set!)
               (let ((idx (vector-ref inst 1)) (src (vector-ref inst 2)))
                 (let ((cell (vector-ref (closure-free (ctx-cl ctx)) idx))
                       (val (vm:reg-ref ctx src)))
                   (cell-value-set! cell val) (loop))))
              ((reg-cell-ref)
               (let ((dst-reg (vector-ref inst 1)) (src-reg (vector-ref inst 2)))
                 (let ((val (vm:reg-ref ctx src-reg)))
                   (let ((extracted (if (cell? val) (cell-value val) val)))
                     (vm:reg-set! ctx dst-reg extracted)) (loop))))
              ((reg-cell-set!)
               (let ((dst-reg (vector-ref inst 1)) (src (vector-ref inst 2)))
                 (let ((cell (vm:reg-ref ctx dst-reg))
                       (val (vm:reg-ref ctx src)))
                   (cell-value-set! cell val) (loop))))
              ((make-cell)
               (let ((src (vector-ref inst 1)) (dst (vector-ref inst 2)))
                 (let ((cell (make-cell-box (vm:reg-ref ctx src))))
                   (vm:reg-set! ctx dst cell)) (loop)))
              ((closure-self)
               (let ((dst (vector-ref inst 1)))
                 (vm:reg-set! ctx dst (ctx-cl ctx)) (loop)))
              (else (error "Unknown instruction" inst))))))))

(define (vm:vm-set-global! vm var val)
  (hash-table-put! (vm-globals vm) var val))
