
;; Register-based VM for Scheme
(use srfi-9)
(use srfi-1)

(define-record-type <vm>
  (make-vm code pc stack cl regs globals)
  vm?
  (code    vm-code    vm-code-set!)
  (pc      vm-pc      vm-pc-set!)
  (stack   vm-stack   vm-stack-set!)
  (cl      vm-cl      vm-cl-set!)
  (regs    vm-regs    vm-regs-set!)
  (globals vm-globals vm-globals-set!))

(define (vm:decode-reg reg)
  (if (symbol? reg)
      (let ((s (symbol->string reg)))
        (if (and (> (string-length s) 1) (char=? (string-ref s 0) #\r))
            (string->number (substring s 1 (string-length s)))
            (error "Invalid register name" reg)))
      reg))

(define (vm:reg-ref vm reg)
  (vector-ref (vm-regs vm) (vm:decode-reg reg)))

(define (vm:reg-set! vm reg val)
  (vector-set! (vm-regs vm) (vm:decode-reg reg) val))

(define-record-type <closure>
  (make-closure-vec label free)
  closure?
  (label closure-label)
  (free  closure-free))

(define-record-type <cell>
  (make-cell-box value)
  cell?
  (value cell-value cell-value-set!))

(define (vm:init-vm code)
  (make-vm code 0 '() #f (make-vector 32 #f) (make-hash-table 'eq?)))

(define (vm:vm-run vm)
  (let loop ()
    (let* ((code (vm-code vm))
           (pc (vm-pc vm)))
      (if (>= pc (vector-length code))
          (vm:reg-ref vm 'r0)
          (let ((inst (vector-ref code pc)))
            (vm-pc-set! vm (+ pc 1))
            (case (vector-ref inst 0)
              ((nop) (loop))
              ((const)
               (let ((reg (vector-ref inst 1)) (val (vector-ref inst 2)))
                 (vm:reg-set! vm reg val) (loop)))
              ((mov)
               (let ((dst (vector-ref inst 1)) (src (vector-ref inst 2)))
                 (vm:reg-set! vm dst (vm:reg-ref vm src)) (loop)))
              ((if)
               (let ((t-label (vector-ref inst 1)) (f-label (vector-ref inst 2)))
                 (if (vm:reg-ref vm 'r0) (vm-pc-set! vm t-label) (vm-pc-set! vm f-label)) (loop)))
              ((global-ref)
               (let ((reg (vector-ref inst 1)) (var (vector-ref inst 2)))
                 (vm:reg-set! vm reg (hash-table-get (vm-globals vm) var)) (loop)))
              ((global-set!)
               (let ((var (vector-ref inst 1)) (src (vector-ref inst 2)))
                 (hash-table-put! (vm-globals vm) var (vm:reg-ref vm src)) (loop)))
              ((jump)
               (let ((label (vector-ref inst 1)))
                 (vm-pc-set! vm label) (loop)))
              ((call)
               (let ((proc-reg (vector-ref inst 1)) (n-args (vector-ref inst 2)))
                 (let ((proc (vm:reg-ref vm proc-reg)))
                   (if (closure? proc)
                       (begin
                         (vm-stack-set! vm (cons (list (vm-pc vm) (vm-cl vm) (vector-copy (vm-regs vm))) (vm-stack vm)))
                         (vm-cl-set! vm proc) (vm-pc-set! vm (closure-label proc)) (loop))
                       (let ((args (let arg-loop ((i 0))
                                     (if (= i n-args) '()
                                         (cons (vm:reg-ref vm (string->symbol (string-append "r" (number->string i))))
                                               (arg-loop (+ i 1))))))
                             (saved-regs (vector-copy (vm-regs vm))))
                         (let ((res (apply proc args)))
                           (vm-regs-set! vm saved-regs)
                           (vm:reg-set! vm 'r0 res) (loop)))))))
              ((tail-call)
               (let ((proc-reg (vector-ref inst 1)) (n-args (vector-ref inst 2)))
                 (let ((proc (vm:reg-ref vm proc-reg)))
                   (if (closure? proc)
                       (begin (vm-cl-set! vm proc) (vm-pc-set! vm (closure-label proc)) (loop))
                       (let ((args (let arg-loop ((i 0))
                                       (if (= i n-args) '()
                                           (cons (vm:reg-ref vm (string->symbol (string-append "r" (number->string i))))
                                                 (arg-loop (+ i 1)))))))
                         (let ((res (apply proc args)))
                           (if (null? (vm-stack vm)) res
                               (let ((ctx (car (vm-stack vm))))
                                 (vm-pc-set! vm (car ctx)) (vm-cl-set! vm (cadr ctx)) (vm-regs-set! vm (caddr ctx))
                                 (vm-stack-set! vm (cdr (vm-stack vm)))
                                 (vm:reg-set! vm 'r0 res) (loop)))))))))
              ((ret)
               (if (null? (vm-stack vm)) (vm:reg-ref vm 'r0)
                   (let ((ctx (car (vm-stack vm)))
                         (res (vm:reg-ref vm 'r0)))
                     (vm-pc-set! vm (car ctx)) (vm-cl-set! vm (cadr ctx)) (vm-regs-set! vm (caddr ctx))
                     (vm-stack-set! vm (cdr (vm-stack vm)))
                     (vm:reg-set! vm 'r0 res) (loop))))
              ((push)
               (let ((reg (vector-ref inst 1)))
                 (vm-stack-set! vm (cons (vm:reg-ref vm reg) (vm-stack vm))) (loop)))
              ((pop)
               (let ((reg (vector-ref inst 1)))
                 (vm:reg-set! vm reg (car (vm-stack vm)))
                 (vm-stack-set! vm (cdr (vm-stack vm))) (loop)))
              ((make-closure)
               (let ((dst (vector-ref inst 1)) (label (vector-ref inst 2)) (free-indices (vector-ref inst 3)))
                 (let ((free-vals (map (lambda (idx) (vm:reg-ref vm idx)) free-indices)))
                   (let ((cl (make-closure-vec label (list->vector free-vals))))
                     (vm:reg-set! vm dst cl)) (loop))))
              ((closure-ref)
               (let ((reg (vector-ref inst 1)) (idx (vector-ref inst 2)))
                 (vm:reg-set! vm reg (vector-ref (closure-free (vm-cl vm)) idx)) (loop)))
              ((closure-cell-ref)
               (let ((reg (vector-ref inst 1)) (idx (vector-ref inst 2)))
                 (let ((val (vector-ref (closure-free (vm-cl vm)) idx)))
                   (let ((extracted (if (cell? val) (cell-value val) val)))
                     (vm:reg-set! vm reg extracted)) (loop))))
              ((closure-set!)
               (let ((idx (vector-ref inst 1)) (src (vector-ref inst 2)))
                 (vector-set! (closure-free (vm-cl vm)) idx (vm:reg-ref vm src)) (loop)))
              ((closure-cell-set!)
               (let ((idx (vector-ref inst 1)) (src (vector-ref inst 2)))
                 (let ((cell (vector-ref (closure-free (vm-cl vm)) idx))
                       (val (vm:reg-ref vm src)))
                   (cell-value-set! cell val) (loop))))
              ((reg-cell-ref)
               (let ((dst-reg (vector-ref inst 1)) (src-reg (vector-ref inst 2)))
                 (let ((val (vm:reg-ref vm src-reg)))
                   (let ((extracted (if (cell? val) (cell-value val) val)))
                     (vm:reg-set! vm dst-reg extracted)) (loop))))
              ((reg-cell-set!)
               (let ((dst-reg (vector-ref inst 1)) (src (vector-ref inst 2)))
                 (let ((cell (vm:reg-ref vm dst-reg))
                       (val (vm:reg-ref vm src)))
                   (cell-value-set! cell val) (loop))))
              ((make-cell)
               (let ((src (vector-ref inst 1)) (dst (vector-ref inst 2)))
                 (let ((cell (make-cell-box (vm:reg-ref vm src))))
                   (vm:reg-set! vm dst cell)) (loop)))
              ((closure-self)
               (let ((dst (vector-ref inst 1)))
                 (vm:reg-set! vm dst (vm-cl vm)) (loop)))
              (else (error "Unknown instruction" inst))))))))

(define (vm:vm-set-global! vm var val)
  (hash-table-put! (vm-globals vm) var val))
