
;; Register-based VM for Scheme
(use srfi-9)
(use srfi-1)

(define-record-type <vm>
  (make-vm-internal globals)
  vm?
  (globals vm-globals vm-globals-set!))

(define-record-type <context>
  (make-context code pc stack cl regs vm)
  context?
  (code    ctx-code    ctx-code-set!)
  (pc      ctx-pc      ctx-pc-set!)
  (stack   ctx-stack   ctx-stack-set!)
  (cl      ctx-cl      ctx-cl-set!)
  (regs    ctx-regs    ctx-regs-set!)
  (vm      ctx-vm      ctx-vm-set!))

(define (vm:decode-reg reg)
  (if (symbol? reg)
      (let ((s (symbol->string reg)))
        (if (and (> (string-length s) 1) (char=? (string-ref s 0) #\r))
            (string->number (substring s 1 (string-length s)))
            (error "Invalid register name" reg)))
      reg))

(define (vm:reg-ref ctx reg)
  (vector-ref (ctx-regs ctx) (vm:decode-reg reg)))

(define (vm:reg-set! ctx reg val)
  (vector-set! (ctx-regs ctx) (vm:decode-reg reg) val))

(define-record-type <closure>
  (make-closure-vec label free)
  closure?
  (label closure-label)
  (free  closure-free))

(define-record-type <cell>
  (make-cell-box value)
  cell?
  (value cell-value cell-value-set!))

(define (vm:init-vm)
  (make-vm-internal (make-hash-table 'eq?)))

(define (vm:init-context vm code)
  (make-context code 0 '() #f (make-vector 64 #f) vm))

(define *vm:continue* (list 'continue))

(define (vm:op-nop ctx inst) *vm:continue*)

(define (vm:op-const ctx inst)
  (let ((reg (vector-ref inst 1))
        (val (vector-ref inst 2)))
    (vm:reg-set! ctx reg val)
    *vm:continue*))

(define (vm:op-mov ctx inst)
  (let ((dst (vector-ref inst 1))
        (src (vector-ref inst 2)))
    (vm:reg-set! ctx dst (vm:reg-ref ctx src))
    *vm:continue*))

(define (vm:op-if ctx inst)
  (let ((t-label (vector-ref inst 1))
        (f-label (vector-ref inst 2)))
    (if (vm:reg-ref ctx 'r0)
        (ctx-pc-set! ctx t-label)
        (ctx-pc-set! ctx f-label))
    *vm:continue*))

(define (vm:op-global-ref ctx inst)
  (let ((reg (vector-ref inst 1))
        (var (vector-ref inst 2)))
    (vm:reg-set! ctx reg (hash-table-get (vm-globals (ctx-vm ctx)) var))
    *vm:continue*))

(define (vm:op-global-set! ctx inst)
  (let ((var (vector-ref inst 1))
        (src (vector-ref inst 2)))
    (hash-table-put! (vm-globals (ctx-vm ctx)) var (vm:reg-ref ctx src))
    *vm:continue*))

(define (vm:op-jump ctx inst)
  (let ((label (vector-ref inst 1)))
    (ctx-pc-set! ctx label)
    *vm:continue*))

(define (vm:fetch-args ctx n-args)
  (let arg-loop ((i 0))
    (if (= i n-args)
        '()
        (cons (vm:reg-ref ctx (string->symbol (string-append "r" (number->string i))))
              (arg-loop (+ i 1))))))

(define (vm:op-call ctx inst)
  (let ((proc-reg (vector-ref inst 1))
        (n-args (vector-ref inst 2)))
    (let ((proc (vm:reg-ref ctx proc-reg)))
      (if (closure? proc)
          (begin
            (ctx-stack-set! ctx (cons (list (ctx-pc ctx) (ctx-cl ctx) (vector-copy (ctx-regs ctx))) (ctx-stack ctx)))
            (ctx-cl-set! ctx proc)
            (ctx-pc-set! ctx (closure-label proc))
            *vm:continue*)
          (let ((args (vm:fetch-args ctx n-args))
                (saved-regs (vector-copy (ctx-regs ctx))))
            (let ((res (apply proc args)))
              (ctx-regs-set! ctx saved-regs)
              (vm:reg-set! ctx 'r0 res)
              *vm:continue*))))))

(define (vm:op-tail-call ctx inst)
  (let ((proc-reg (vector-ref inst 1))
        (n-args (vector-ref inst 2)))
    (let ((proc (vm:reg-ref ctx proc-reg)))
      (if (closure? proc)
          (begin
            (ctx-cl-set! ctx proc)
            (ctx-pc-set! ctx (closure-label proc))
            *vm:continue*)
          (let ((args (vm:fetch-args ctx n-args)))
            (let ((res (apply proc args)))
              (if (null? (ctx-stack ctx))
                  res
                  (let ((ctx-data (car (ctx-stack ctx))))
                    (ctx-pc-set! ctx (car ctx-data))
                    (ctx-cl-set! ctx (cadr ctx-data))
                    (ctx-regs-set! ctx (caddr ctx-data))
                    (ctx-stack-set! ctx (cdr (ctx-stack ctx)))
                    (vm:reg-set! ctx 'r0 res)
                    *vm:continue*))))))))

(define (vm:op-ret ctx inst)
  (if (null? (ctx-stack ctx))
      (vm:reg-ref ctx 'r0)
      (let ((ctx-data (car (ctx-stack ctx)))
            (res (vm:reg-ref ctx 'r0)))
        (ctx-pc-set! ctx (car ctx-data))
        (ctx-cl-set! ctx (cadr ctx-data))
        (ctx-regs-set! ctx (caddr ctx-data))
        (ctx-stack-set! ctx (cdr (ctx-stack ctx)))
        (vm:reg-set! ctx 'r0 res)
        *vm:continue*)))

(define (vm:op-make-closure ctx inst)
  (let ((dst (vector-ref inst 1))
        (label (vector-ref inst 2))
        (free-indices (vector-ref inst 3)))
    (let ((free-vals (map (lambda (idx) (vm:reg-ref ctx idx)) free-indices)))
      (let ((cl (make-closure-vec label (list->vector free-vals))))
        (vm:reg-set! ctx dst cl))
      *vm:continue*)))

(define (vm:op-closure-ref ctx inst)
  (let ((reg (vector-ref inst 1))
        (idx (vector-ref inst 2)))
    (vm:reg-set! ctx reg (vector-ref (closure-free (ctx-cl ctx)) idx))
    *vm:continue*))

(define (vm:op-closure-cell-ref ctx inst)
  (let ((reg (vector-ref inst 1))
        (idx (vector-ref inst 2)))
    (let ((val (vector-ref (closure-free (ctx-cl ctx)) idx)))
      (let ((extracted (if (cell? val) (cell-value val) val)))
        (vm:reg-set! ctx reg extracted))
      *vm:continue*)))

(define (vm:op-closure-set! ctx inst)
  (let ((idx (vector-ref inst 1))
        (src (vector-ref inst 2)))
    (vector-set! (closure-free (ctx-cl ctx)) idx (vm:reg-ref ctx src))
    *vm:continue*))

(define (vm:op-closure-cell-set! ctx inst)
  (let ((idx (vector-ref inst 1))
        (src (vector-ref inst 2)))
    (let ((cell (vector-ref (closure-free (ctx-cl ctx)) idx))
          (val (vm:reg-ref ctx src)))
      (cell-value-set! cell val)
      *vm:continue*)))

(define (vm:op-reg-cell-ref ctx inst)
  (let ((dst-reg (vector-ref inst 1))
        (src-reg (vector-ref inst 2)))
    (let ((val (vm:reg-ref ctx src-reg)))
      (let ((extracted (if (cell? val) (cell-value val) val)))
        (vm:reg-set! ctx dst-reg extracted))
      *vm:continue*)))

(define (vm:op-reg-cell-set! ctx inst)
  (let ((dst-reg (vector-ref inst 1))
        (src (vector-ref inst 2)))
    (let ((cell (vm:reg-ref ctx dst-reg))
          (val (vm:reg-ref ctx src)))
      (cell-value-set! cell val)
      *vm:continue*)))

(define (vm:op-make-cell ctx inst)
  (let ((src (vector-ref inst 1))
        (dst (vector-ref inst 2)))
    (let ((cell (make-cell-box (vm:reg-ref ctx src))))
      (vm:reg-set! ctx dst cell))
    *vm:continue*))

(define (vm:op-closure-self ctx inst)
  (let ((dst (vector-ref inst 1)))
    (vm:reg-set! ctx dst (ctx-cl ctx))
    *vm:continue*))

(define (vm:vm-run ctx)
  (let loop ()
    (let* ((code (ctx-code ctx))
           (pc (ctx-pc ctx)))
      (if (>= pc (vector-length code))
          (vm:reg-ref ctx 'r0)
          (let* ((inst (vector-ref code pc))
                 (op (vector-ref inst 0)))
            (ctx-pc-set! ctx (+ pc 1))
            (let ((res (case op
                         ((nop)               (vm:op-nop ctx inst))
                         ((const)             (vm:op-const ctx inst))
                         ((mov)               (vm:op-mov ctx inst))
                         ((if)                (vm:op-if ctx inst))
                         ((global-ref)        (vm:op-global-ref ctx inst))
                         ((global-set!)       (vm:op-global-set! ctx inst))
                         ((jump)              (vm:op-jump ctx inst))
                         ((call)              (vm:op-call ctx inst))
                         ((tail-call)         (vm:op-tail-call ctx inst))
                         ((ret)               (vm:op-ret ctx inst))
                         ((make-closure)      (vm:op-make-closure ctx inst))
                         ((closure-ref)       (vm:op-closure-ref ctx inst))
                         ((closure-cell-ref)  (vm:op-closure-cell-ref ctx inst))
                         ((closure-set!)      (vm:op-closure-set! ctx inst))
                         ((closure-cell-set!) (vm:op-closure-cell-set! ctx inst))
                         ((reg-cell-ref)      (vm:op-reg-cell-ref ctx inst))
                         ((reg-cell-set!)     (vm:op-reg-cell-set! ctx inst))
                         ((make-cell)         (vm:op-make-cell ctx inst))
                         ((closure-self)      (vm:op-closure-self ctx inst))
                         (else (error "Unknown instruction" inst)))))
              (if (eq? res *vm:continue*)
                  (loop)
                  res)))))))

(define (vm:vm-set-global! vm var val)
  (hash-table-put! (vm-globals vm) var val))
