
(define (closure-conversion expr)
  (let ((lifted-defs '()))

    (define (normalize-define expr)
      (if (and (pair? expr) (eq? (car expr) 'define))
          (let ((head (cadr expr))
                (body (cddr expr)))
            (if (pair? head)
                `(define ,(car head) (lambda ,(cdr head) ,@body))
                expr))
          expr))

    ;; --- Set Primitives ---
    (define (set-union s1 s2)
      (if (null? s1) s2
          (let ((rest (set-union (cdr s1) s2)))
            (if (memq (car s1) s2) rest (cons (car s1) rest)))))

    (define (set-minus s1 s2)
      (if (null? s1) '()
          (let ((rest (set-minus (cdr s1) s2)))
            (if (memq (car s1) s2) rest (cons (car s1) rest)))))

    ;; --- Analysis: Free Variables ---
    (define (analyze-free-vars expr bound-vars)
      (cond
        ((symbol? expr)
        (if (memq expr bound-vars) (list expr) '())) 
        ((not (pair? expr)) '())
        ((eq? (car expr) 'quote) '())
        ((eq? (car expr) 'if)
        (set-union (analyze-free-vars (cadr expr) bound-vars)
                    (set-union (analyze-free-vars (caddr expr) bound-vars)
                              (if (null? (cdddr expr)) '() (analyze-free-vars (cadddr expr) bound-vars)))))
        ((eq? (car expr) 'begin)
        (let loop ((exprs (cdr expr)))
          (if (null? exprs) '()
              (set-union (analyze-free-vars (car exprs) bound-vars)
                          (loop (cdr exprs))))))
        ((eq? (car expr) 'set!)
        (let ((var (cadr expr))
              (val (caddr expr)))
          (set-union (if (memq var bound-vars) (list var) '())
                      (analyze-free-vars val bound-vars))))
        ((eq? (car expr) 'lambda)
        (let ((params (cadr expr))
              (body (cddr expr)))
          (let ((new-bound (if (list? params) params 
                                (let loop ((p params)) (if (pair? p) (cons (car p) (loop (cdr p))) (list p))))))
            (let ((body-free (let loop ((exprs body))
                                (if (null? exprs) '()
                                    (set-union (analyze-free-vars (car exprs) (append new-bound bound-vars))
                                              (loop (cdr exprs)))))))
              (set-minus body-free new-bound)))))
        ((eq? (car expr) 'let)
        (let ((bindings (cadr expr))
              (body (cddr expr)))
          (let ((vars (map car bindings))
                (vals (map cadr bindings)))
            (set-union (let loop ((vs vals))
                          (if (null? vs) '()
                              (set-union (analyze-free-vars (car vs) bound-vars)
                                        (loop (cdr vs)))))
                        (let ((body-free (let loop ((exprs body))
                                          (if (null? exprs) '()
                                              (set-union (analyze-free-vars (car exprs) (append vars bound-vars))
                                                          (loop (cdr exprs)))))))
                          (set-minus body-free vars))))))
        (else
        ;; Application
        (let loop ((exprs expr))
          (if (null? exprs) '()
              (set-union (analyze-free-vars (car exprs) bound-vars)
                          (loop (cdr exprs))))))))

    ;; --- Analysis: Mutability ---
    (define (analyze-mutated-vars expr)
      (cond
        ((pair? expr)
        (cond
          ((eq? (car expr) 'quote) '())
          ((eq? (car expr) 'set!)
          (cons (cadr expr) (analyze-mutated-vars (caddr expr))))
          ((eq? (car expr) 'lambda)
          (let loop ((body (cddr expr)))
            (if (null? body) '()
                (set-union (analyze-mutated-vars (car body)) (loop (cdr body))))))
          (else
          (let loop ((exprs expr))
            (if (null? exprs) '()
                (set-union (analyze-mutated-vars (car exprs)) 
                            (loop (cdr exprs))))))))
        (else '())))

    ;; --- Phase 2: Boxing Transformation ---
    (define (box-transform expr mutated-vars)
      (cond
        ((symbol? expr)
        (if (memq expr mutated-vars)
            `(tuple-ref ,expr 0)
            expr))
        ((not (pair? expr)) expr)
        ((eq? (car expr) 'quote) expr)
        ((eq? (car expr) 'if)
        `(if ,(box-transform (cadr expr) mutated-vars)
              ,(box-transform (caddr expr) mutated-vars)
              ,(if (null? (cdddr expr)) '() (box-transform (cadddr expr) mutated-vars))))
        ((eq? (car expr) 'set!)
        (let ((var (cadr expr))
              (val (box-transform (caddr expr) mutated-vars)))
          (if (memq var mutated-vars)
              `(tuple-set! ,var 0 ,val)
              `(set! ,var ,val))))
        ((eq? (car expr) 'begin)
        `(begin ,@(map (lambda (e) (box-transform e mutated-vars)) (cdr expr))))
        ((eq? (car expr) 'lambda)
        (let ((params (cadr expr))
              (body (cddr expr)))
          (let* ((flat-params (if (list? params) params 
                                  (let loop ((p params)) (if (pair? p) (cons (car p) (loop (cdr p))) (list p)))))
                  (params-to-box (let loop ((p flat-params))
                                  (if (null? p) '()
                                      (if (memq (car p) mutated-vars)
                                          (cons (car p) (loop (cdr p)))
                                          (loop (cdr p)))))))
            `(lambda ,params
                ,(if (null? params-to-box)
                    (let ((new-body (map (lambda (e) (box-transform e mutated-vars)) body)))
                      (if (= (length new-body) 1) (car new-body) `(begin ,@new-body)))
                    `(let ,(map (lambda (v) `(,v (tuple ,v))) params-to-box)
                        ,@(map (lambda (e) (box-transform e mutated-vars)) body)))))))
        ((eq? (car expr) 'let)
        (let ((bindings (cadr expr))
              (body (cddr expr)))
          (let* ((vars (map car bindings))
                  (vals (map (lambda (v) (box-transform v mutated-vars)) (map cadr bindings)))
                  (vars-to-box (let loop ((v vars))
                                (if (null? v) '()
                                    (if (memq (car v) mutated-vars)
                                        (cons (car v) (loop (cdr v)))
                                        (loop (cdr v)))))))
            `(let ,(map list vars vals)
                ,@(if (null? vars-to-box)
                      (map (lambda (e) (box-transform e mutated-vars)) body)
                      `((let ,(map (lambda (v) `(,v (tuple ,v))) vars-to-box)
                          ,@(map (lambda (e) (box-transform e mutated-vars)) body))))))))
        (else
        (map (lambda (e) (box-transform e mutated-vars)) expr))))

    ;; --- Phase 3: Lambda Lifting (Closure Conversion) ---
    (define (lift-transform expr bound-vars)
      (cond
        ((symbol? expr) expr)
        ((not (pair? expr)) expr)
        ((eq? (car expr) 'quote) expr)
        ((eq? (car expr) 'if)
        `(if ,(lift-transform (cadr expr) bound-vars)
              ,(lift-transform (caddr expr) bound-vars)
              ,(if (null? (cdddr expr)) '() (lift-transform (cadddr expr) bound-vars))))
        ((eq? (car expr) 'set!)
        `(set! ,(cadr expr) ,(lift-transform (caddr expr) bound-vars)))
        ((eq? (car expr) 'begin)
        `(begin ,@(map (lambda (e) (lift-transform e bound-vars)) (cdr expr))))
        ((eq? (car expr) 'let)
        (let ((bindings (cadr expr))
              (body (cddr expr)))
          `(let ,(map (lambda (b) (list (car b) (lift-transform (cadr b) bound-vars))) bindings)
              ,@(map (lambda (e) (lift-transform e (append (map car bindings) bound-vars))) body))))
        ((eq? (car expr) 'lambda)
        (let ((params (cadr expr))
              (body (cddr expr)))
            (let* ((flat-params (if (list? params) params 
                                    (let loop ((p params)) (if (pair? p) (cons (car p) (loop (cdr p))) (list p)))))
                  (inner-bound (append flat-params bound-vars))
                  (free (analyze-free-vars expr bound-vars))
                  (transformed-body (map (lambda (e) (lift-transform e inner-bound)) body))
                  (lifted-name (if (null? free)
                                    (gensym "noname_subr_")
                                    (gensym "noname_close_"))))
              
              (if (null? free)
                  (let ((def `(define ,lifted-name
                                (lambda ,params
                                  ,@transformed-body))))
                    (set! lifted-defs (cons def lifted-defs))
                    lifted-name) ;; Return the function name itself to be used as a value or called
                  (let ((def `(define ,lifted-name
                                (lambda ,free
                                  (lambda ,params
                                    ,@transformed-body)))))
                    (set! lifted-defs (cons def lifted-defs))
                    `(,lifted-name ,@free))))))
        (else
        (map (lambda (e) (lift-transform e bound-vars)) expr))))

    ;; --- Main Driver ---
    (let* ((expr (normalize-define expr))
            (def-name (cadr expr))
            (def-expr (caddr expr))
            (mutated (analyze-mutated-vars expr)))
      
      (let ((boxed-expr (box-transform expr mutated)))
        (if (eq? (car boxed-expr) 'define)
            (let ((b-name (cadr boxed-expr))
                  (b-val (caddr boxed-expr)))
                (if (eq? (car b-val) 'lambda)
                    (let* ((params (cadr b-val))
                          (body (cddr b-val))
                          (flat-params (if (list? params) params 
                                            (let loop ((p params)) (if (pair? p) (cons (car p) (loop (cdr p))) (list p)))))
                          (transformed-body (map (lambda (e) (lift-transform e flat-params)) body)))
                      
                      (let ((final-def `(define ,b-name (lambda ,params ,@transformed-body))))
                        (append (reverse lifted-defs) (list final-def))))
                    (list boxed-expr)))
            (list boxed-expr))))))

