(let ((v (make-u8vector 12)))
  (display "Testing u8vector-uint32-set! at offset 0: ")
  (u8vector-uint32-set! v 0 #x12345678)
  (let ((val (u8vector-uint32-ref v 0)))
    (display (number->string val 16))
    (newline)
    (if (= val #x12345678)
        (display "PASS\n")
        (display "FAIL\n")))

  (display "Testing u8vector-int32-set! at offset 4: ")
  (u8vector-int32-set! v 4 -1)
  (let ((val (u8vector-int32-ref v 4)))
    (display val)
    (newline)
    (if (= val -1)
        (display "PASS\n")
        (display "FAIL\n")))

  (display "Testing u8vector-uint32-ref at offset 4 (as uint32): ")
  (let ((val (u8vector-uint32-ref v 4)))
    (display (number->string val 16))
    (newline)
    (if (= val #xffffffff)
        (display "PASS\n")
        (display "FAIL\n")))

  (display "Testing u8vector-int32-set! with positive value at offset 8: ")
  (u8vector-int32-set! v 8 #x7fffffff)
  (let ((val (u8vector-int32-ref v 8)))
    (display (number->string val 16))
    (newline)
    (if (= val #x7fffffff)
        (display "PASS\n")
        (display "FAIL\n")))
)
