// Copyright (c) 2004-2026 Yoshikatsu Fujita / LittleWing Company Limited.
// See LICENSE file for terms and conditions of use.

#ifndef SUBR_H_INCLUDED
#define SUBR_H_INCLUDED

#include "core.h"
#include "object.h"

#define SUBR extern "C" scm_obj_t

void init_subr_base();
void init_subr_arith();
void init_subr_hash();
void init_subr_cxr();
void init_subr_env();
void init_subr_io();
void init_subr_misc();
void init_subr_cffi();
void init_subr_uvector();
void init_subr_fiber();
void init_subr_asio();
void init_subr_net();
void init_subr_vertex();
void init_subr_dialogflow();


SUBR subr_fiber(scm_obj_t self, scm_obj_t closure);
SUBR subr_fiber_yield(scm_obj_t self);
SUBR subr_fiber_sleep_for(scm_obj_t self, scm_obj_t msec);
SUBR subr_future_get(scm_obj_t self, scm_obj_t future_obj);
SUBR subr_future_wait(scm_obj_t self, scm_obj_t future_obj);
SUBR subr_future_wait_for(scm_obj_t self, scm_obj_t future_obj, scm_obj_t msec);
SUBR subr_future_p(scm_obj_t self, scm_obj_t obj);

SUBR subr_put_string_async(scm_obj_t self, scm_obj_t port, scm_obj_t str);

SUBR subr_https_get(scm_obj_t self, scm_obj_t url, scm_obj_t port);
SUBR subr_https_get_async(scm_obj_t self, scm_obj_t url, scm_obj_t port);

SUBR subr_num_add(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_num_sub(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_num_mul(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_num_div(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_num_eq(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_num_lt(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_num_gt(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_num_le(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_num_ge(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_zero_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_remainder(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_quotient(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_exact_to_inexact(scm_obj_t self, scm_obj_t a1);
SUBR subr_odd_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_even_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_sqrt(scm_obj_t self, scm_obj_t a1);
SUBR subr_sin(scm_obj_t self, scm_obj_t a1);
SUBR subr_cos(scm_obj_t self, scm_obj_t a1);
SUBR subr_tan(scm_obj_t self, scm_obj_t a1);
SUBR subr_atan(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_modulo(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_append(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_car(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdr(scm_obj_t self, scm_obj_t a1);
SUBR subr_set_car(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_set_cdr(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_length(scm_obj_t self, scm_obj_t a1);
SUBR subr_list_ref(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_memq(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_memv(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_assq(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_assv(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_not(scm_obj_t self, scm_obj_t a1);
SUBR subr_boolean_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_char_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_pair_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_null_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_eq_p(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_symbol_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_string_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_vector_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_hashtable_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_tuple_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_continuation_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_list_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_vector_length(scm_obj_t self, scm_obj_t a1);
SUBR subr_vector_ref(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_vector_set(scm_obj_t self, scm_obj_t a1, scm_obj_t a2, scm_obj_t a3);
SUBR subr_string_length(scm_obj_t self, scm_obj_t a1);
SUBR subr_string_ref(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_string_eq(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_string_lt(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_string_gt(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_string_le(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_string_ge(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_char_eq(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_char_lt(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_char_gt(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_char_le(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_char_ge(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_char_numeric_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_eqv_p(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_exact_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_inexact_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_infinite_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_integer_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_number_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_nan_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_procedure_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_real_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_environment_macros(scm_obj_t self, scm_obj_t a1);
SUBR subr_environment_variables(scm_obj_t self, scm_obj_t a1);
SUBR subr_environment_macro_ref(scm_obj_t self, scm_obj_t a1);
SUBR subr_environment_variable_ref(scm_obj_t self, scm_obj_t a1);
SUBR subr_environment_macro_contains(scm_obj_t self, scm_obj_t a1);
SUBR subr_environment_variable_contains(scm_obj_t self, scm_obj_t a1);
SUBR subr_current_environment(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_interaction_environment(scm_obj_t self);
SUBR subr_system_environment(scm_obj_t self);
SUBR subr_equal_hash(scm_obj_t self, scm_obj_t a1);
SUBR subr_hashtable_delete(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_hashtable_clear(scm_obj_t self, scm_obj_t a1);
SUBR subr_current_input_port(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_current_output_port(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_current_error_port(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_standard_input_port(scm_obj_t self);
SUBR subr_standard_output_port(scm_obj_t self);
SUBR subr_standard_error_port(scm_obj_t self);
SUBR subr_file_exists_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_eof_object_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_fixnum_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_undefined(scm_obj_t self);
SUBR subr_unspecified(scm_obj_t self);
SUBR subr_undefined_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_unspecified_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_cyclic_object_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_tuple_set(scm_obj_t self, scm_obj_t a1, scm_obj_t a2, scm_obj_t a3);
SUBR subr_tuple_ref(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_time_usage(scm_obj_t self);

SUBR subr_caar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cadr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cddr(scm_obj_t self, scm_obj_t a1);
SUBR subr_caaar(scm_obj_t self, scm_obj_t a1);
SUBR subr_caadr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cadar(scm_obj_t self, scm_obj_t a1);
SUBR subr_caddr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdaar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdadr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cddar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdddr(scm_obj_t self, scm_obj_t a1);
SUBR subr_caaaar(scm_obj_t self, scm_obj_t a1);
SUBR subr_caaadr(scm_obj_t self, scm_obj_t a1);
SUBR subr_caadar(scm_obj_t self, scm_obj_t a1);
SUBR subr_caaddr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cadaar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cadadr(scm_obj_t self, scm_obj_t a1);
SUBR subr_caddar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cadddr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdaaar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdaadr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdadar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdaddr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cddaar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cddadr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdddar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cddddr(scm_obj_t self, scm_obj_t a1);
SUBR subr_caaaaar(scm_obj_t self, scm_obj_t a1);
SUBR subr_caaaadr(scm_obj_t self, scm_obj_t a1);
SUBR subr_caaadar(scm_obj_t self, scm_obj_t a1);
SUBR subr_caaaddr(scm_obj_t self, scm_obj_t a1);
SUBR subr_caadaar(scm_obj_t self, scm_obj_t a1);
SUBR subr_caadadr(scm_obj_t self, scm_obj_t a1);
SUBR subr_caaddar(scm_obj_t self, scm_obj_t a1);
SUBR subr_caadddr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cadaaar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cadaadr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cadadar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cadaddr(scm_obj_t self, scm_obj_t a1);
SUBR subr_caddaar(scm_obj_t self, scm_obj_t a1);
SUBR subr_caddadr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cadddar(scm_obj_t self, scm_obj_t a1);
SUBR subr_caddddr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdaaaar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdaaadr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdaadar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdaaddr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdadaar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdadadr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdaddar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdadddr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cddaaar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cddaadr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cddadar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cddaddr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdddaar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdddadr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cddddar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdddddr(scm_obj_t self, scm_obj_t a1);

#endif  // SUBR_H_INCLUDED
