// Copyright (c) 2004-2026 Yoshikatsu Fujita / LittleWing Company Limited.
// See LICENSE file for terms and conditions of use.

#ifndef SUBR_H_INCLUDED
#define SUBR_H_INCLUDED

#include "core.h"
#include "object.h"

#define SUBR extern "C" scm_obj_t

void init_subr_base();
void init_subr_arith();
void init_subr_hash();
void init_subr_cxr();
void init_subr_env();
void init_subr_io();
void init_subr_misc();
void init_subr_cffi();
void init_subr_uvector();
void init_subr_fiber();
void init_subr_asio();
void init_subr_net();
void init_subr_vertex();
void init_subr_dialogflow();

SUBR subr_append(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_apply(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_assertion_violation(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_assoc(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_assq(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_assv(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_atan(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_boolean_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_caaaaar(scm_obj_t self, scm_obj_t a1);
SUBR subr_caaaadr(scm_obj_t self, scm_obj_t a1);
SUBR subr_caaaar(scm_obj_t self, scm_obj_t a1);
SUBR subr_caaadar(scm_obj_t self, scm_obj_t a1);
SUBR subr_caaaddr(scm_obj_t self, scm_obj_t a1);
SUBR subr_caaadr(scm_obj_t self, scm_obj_t a1);
SUBR subr_caaar(scm_obj_t self, scm_obj_t a1);
SUBR subr_caadaar(scm_obj_t self, scm_obj_t a1);
SUBR subr_caadadr(scm_obj_t self, scm_obj_t a1);
SUBR subr_caadar(scm_obj_t self, scm_obj_t a1);
SUBR subr_caaddar(scm_obj_t self, scm_obj_t a1);
SUBR subr_caadddr(scm_obj_t self, scm_obj_t a1);
SUBR subr_caaddr(scm_obj_t self, scm_obj_t a1);
SUBR subr_caadr(scm_obj_t self, scm_obj_t a1);
SUBR subr_caar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cadaaar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cadaadr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cadaar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cadadar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cadaddr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cadadr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cadar(scm_obj_t self, scm_obj_t a1);
SUBR subr_caddaar(scm_obj_t self, scm_obj_t a1);
SUBR subr_caddadr(scm_obj_t self, scm_obj_t a1);
SUBR subr_caddar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cadddar(scm_obj_t self, scm_obj_t a1);
SUBR subr_caddddr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cadddr(scm_obj_t self, scm_obj_t a1);
SUBR subr_caddr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cadr(scm_obj_t self, scm_obj_t a1);
SUBR subr_call_with_values(scm_obj_t self, scm_obj_t producer, scm_obj_t consumer);
SUBR subr_car(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdaaaar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdaaadr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdaaar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdaadar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdaaddr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdaadr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdaar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdadaar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdadadr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdadar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdaddar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdadddr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdaddr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdadr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cddaaar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cddaadr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cddaar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cddadar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cddaddr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cddadr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cddar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdddaar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdddadr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdddar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cddddar(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdddddr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cddddr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdddr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cddr(scm_obj_t self, scm_obj_t a1);
SUBR subr_cdr(scm_obj_t self, scm_obj_t a1);
SUBR subr_char_alphabetic_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_char_ci_eq(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_char_ci_ge(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_char_ci_gt(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_char_ci_le(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_char_ci_lt(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_char_downcase(scm_obj_t self, scm_obj_t a1);
SUBR subr_char_eq(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_char_ge(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_char_gt(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_char_le(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_char_lower_case_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_char_lt(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_char_numeric_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_char_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_char_to_integer(scm_obj_t self, scm_obj_t a1);
SUBR subr_char_upcase(scm_obj_t self, scm_obj_t a1);
SUBR subr_char_upper_case_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_char_whitespace_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_close_port(scm_obj_t self, scm_obj_t a1);
SUBR subr_codegen_and_run(scm_obj_t self, scm_obj_t inst_list);
SUBR subr_codegen_cdecl_callback(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_codegen_cdecl_callout(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_collect(scm_obj_t self);
SUBR subr_cons(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_cons_star(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_copy_environment_macros(scm_obj_t self, scm_obj_t a1, scm_obj_t a2, scm_obj_t a3);
SUBR subr_copy_environment_variables(scm_obj_t self, scm_obj_t a1, scm_obj_t a2, scm_obj_t a3);
SUBR subr_cos(scm_obj_t self, scm_obj_t a1);
SUBR subr_current_collect_trip_bytes(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_current_environment(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_current_error_port(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_current_input_port(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_current_output_port(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_cyclic_object_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_dialogflow_cx_detect_intent_async(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_dialogflow_cx_detect_intent(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_display(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_dynamic_wind(scm_obj_t self, scm_obj_t pre, scm_obj_t value, scm_obj_t post);
SUBR subr_environment_macro_contains(scm_obj_t self, scm_obj_t a1);
SUBR subr_environment_macro_ref(scm_obj_t self, scm_obj_t a1);
SUBR subr_environment_macro_set(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_environment_macros(scm_obj_t self, scm_obj_t a1);
SUBR subr_environment_variable_contains(scm_obj_t self, scm_obj_t a1);
SUBR subr_environment_variable_ref(scm_obj_t self, scm_obj_t a1);
SUBR subr_environment_variable_set(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_environment_variables(scm_obj_t self, scm_obj_t a1);
SUBR subr_eof_object_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_eq_p(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_equal_hash(scm_obj_t self, scm_obj_t a1);
SUBR subr_equal_p(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_eqv_p(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_error(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_even_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_exact_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_exact_to_inexact(scm_obj_t self, scm_obj_t a1);
SUBR subr_exit(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_fiber(scm_obj_t self, scm_obj_t closure);
SUBR subr_fiber_sleep_for(scm_obj_t self, scm_obj_t msec);
SUBR subr_fiber_yield(scm_obj_t self);
SUBR subr_file_exists_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_fixnum_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_flush_output_port(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_format(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_future_get(scm_obj_t self, scm_obj_t obj);
SUBR subr_future_p(scm_obj_t self, scm_obj_t obj);
SUBR subr_future_wait_for(scm_obj_t self, scm_obj_t obj, scm_obj_t msec);
SUBR subr_future_wait(scm_obj_t self, scm_obj_t obj);
SUBR subr_generate_content_async(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_generate_content(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_gensym(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_get_bytevector_n_async(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_get_bytevector_n(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_hashtable_alist(scm_obj_t self, scm_obj_t a1);
SUBR subr_hashtable_clear(scm_obj_t self, scm_obj_t a1);
SUBR subr_hashtable_contains(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_hashtable_delete(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_hashtable_entries(scm_obj_t self, scm_obj_t a1);
SUBR subr_hashtable_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_hashtable_ref(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_hashtable_set(scm_obj_t self, scm_obj_t a1, scm_obj_t a2, scm_obj_t a3);
SUBR subr_https_get_async(scm_obj_t self, scm_obj_t url_obj, scm_obj_t port_obj);
SUBR subr_https_get(scm_obj_t self, scm_obj_t url_obj, scm_obj_t port_obj);
SUBR subr_inexact_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_inexact_to_exact(scm_obj_t self, scm_obj_t a1);
SUBR subr_infinite_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_integer_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_integer_to_char(scm_obj_t self, scm_obj_t a1);
SUBR subr_interaction_environment(scm_obj_t self);
SUBR subr_length(scm_obj_t self, scm_obj_t a1);
SUBR subr_list_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_list_ref(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_list(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_list_to_string(scm_obj_t self, scm_obj_t a1);
SUBR subr_list_to_vector(scm_obj_t self, scm_obj_t a1);
SUBR subr_list_transpose_plus(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_list_transpose(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_load_shared_object(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_lookup_process_environment(scm_obj_t self, scm_obj_t a1);
SUBR subr_lookup_shared_object(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_make_environment(scm_obj_t self, scm_obj_t a1);
SUBR subr_make_eq_hashtable(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_make_equal_hashtable(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_make_eqv_hashtable(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_make_string(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_make_tuple(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_make_u8vector_mapping(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_make_u8vector(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_make_vector(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_max(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_member(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_memq(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_memv(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_min(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_modulo(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_nan_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_negative_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_newline(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_not(scm_obj_t self, scm_obj_t a1);
SUBR subr_null_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_num_add(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_number_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_number_to_string(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_num_div(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_num_eq(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_num_ge(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_num_gt(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_num_le(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_num_lt(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_num_mul(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_num_sub(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_odd_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_open_file_input_port(scm_obj_t self, scm_obj_t a1);
SUBR subr_open_file_output_port(scm_obj_t self, scm_obj_t a1);
SUBR subr_open_string_output_port(scm_obj_t self);
SUBR subr_pair_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_positive_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_procedure_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_put_char(scm_obj_t self, scm_obj_t port, scm_obj_t ch);
SUBR subr_put_string_async(scm_obj_t self, scm_obj_t port, scm_obj_t str);
SUBR subr_put_string(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_quotient(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_read(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_real_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_remainder(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_reverse(scm_obj_t self, scm_obj_t a1);
SUBR subr_round(scm_obj_t self, scm_obj_t a1);
SUBR subr_safepoint(scm_obj_t self);
SUBR subr_set_car(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_set_cdr(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_sin(scm_obj_t self, scm_obj_t a1);
SUBR subr_sqrt(scm_obj_t self, scm_obj_t a1);
SUBR subr_standard_error_port(scm_obj_t self);
SUBR subr_standard_input_port(scm_obj_t self);
SUBR subr_standard_output_port(scm_obj_t self);
SUBR subr_string_append(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_string_ci_eq(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_string_ci_ge(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_string_ci_gt(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_string_ci_le(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_string_ci_lt(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_string_copy(scm_obj_t self, scm_obj_t a1);
SUBR subr_string_eq(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_string_ge(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_string_gt(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_string_length(scm_obj_t self, scm_obj_t a1);
SUBR subr_string_le(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_string_lt(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_string_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_string_ref(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_string(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_string_to_list(scm_obj_t self, scm_obj_t a1);
SUBR subr_string_to_number(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_string_to_symbol(scm_obj_t self, scm_obj_t a1);
SUBR subr_string_utf8_nul(scm_obj_t self, scm_obj_t a1);
SUBR subr_substring(scm_obj_t self, scm_obj_t a1, scm_obj_t a2, scm_obj_t a3);
SUBR subr_symbol_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_symbol_to_string(scm_obj_t self, scm_obj_t a1);
SUBR subr_syntax_violation(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_system_environment(scm_obj_t self);
SUBR subr_tan(scm_obj_t self, scm_obj_t a1);
SUBR subr_time_usage(scm_obj_t self);
SUBR subr_tuple_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_tuple_ref(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_tuple(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_tuple_set(scm_obj_t self, scm_obj_t a1, scm_obj_t a2, scm_obj_t a3);
SUBR subr_u8vector_int32_ref(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_u8vector_int32_set(scm_obj_t self, scm_obj_t a1, scm_obj_t a2, scm_obj_t a3);
SUBR subr_u8vector_length(scm_obj_t self, scm_obj_t a1);
SUBR subr_u8vector_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_u8vector_ref(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_u8vector_set(scm_obj_t self, scm_obj_t a1, scm_obj_t a2, scm_obj_t a3);
SUBR subr_u8vector_uint32_ref(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_u8vector_uint32_set(scm_obj_t self, scm_obj_t a1, scm_obj_t a2, scm_obj_t a3);
SUBR subr_undefined_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_undefined(scm_obj_t self);
SUBR subr_undefine(scm_obj_t self, scm_obj_t a1);
SUBR subr_unspecified_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_unspecified(scm_obj_t self);
SUBR subr_uuid(scm_obj_t self);
SUBR subr_values(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_vector_length(scm_obj_t self, scm_obj_t a1);
SUBR subr_vector_p(scm_obj_t self, scm_obj_t a1);
SUBR subr_vector_ref(scm_obj_t self, scm_obj_t a1, scm_obj_t a2);
SUBR subr_vector(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_vector_set(scm_obj_t self, scm_obj_t a1, scm_obj_t a2, scm_obj_t a3);
SUBR subr_vector_to_list(scm_obj_t self, scm_obj_t a1);
SUBR subr_with_cpp_exception_handler(scm_obj_t self, scm_obj_t handler, scm_obj_t thunk);
SUBR subr_write(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_write_ss(scm_obj_t self, int argc, scm_obj_t argv[]);
SUBR subr_zero_p(scm_obj_t self, scm_obj_t a1);
SUBR thunk_string_output_port_extract(scm_obj_t self, int argc, scm_obj_t argv[]);

#endif  // SUBR_H_INCLUDED
